# Generated by Django 6.0.4 on 2026-04-12 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_attribute_options_alter_attributevalue_options_and_more'),
        ('compatibility', '0001_initial'),
        ('vehicles', '0002_alter_vehicleengine_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfitment',
            options={'ordering': ('product__name',), 'verbose_name': 'Применимость товара', 'verbose_name_plural': 'Применимость товаров'},
        ),
        migrations.AlterField(
            model_name='productfitment',
            name='is_exact',
            field=models.BooleanField(default=True, verbose_name='Точное соответствие'),
        ),
        migrations.AlterField(
            model_name='productfitment',
            name='modification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='vehicles.vehiclemodification', verbose_name='Модификация'),
        ),
        migrations.AlterField(
            model_name='productfitment',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='productfitment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='catalog.product', verbose_name='Товар'),
        ),
    ]
