# Generated by Django 6.0.4 on 2026-05-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compatibility", "0002_alter_productfitment_options_and_more"),
        ("vehicles", "0002_alter_vehicleengine_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productfitment",
            name="article_number",
            field=models.CharField(blank=True, db_index=True, default="", max_length=128, verbose_name="Auto_DB_Pro article number"),
        ),
        migrations.AddField(
            model_name="productfitment",
            name="autodb_article_key",
            field=models.CharField(blank=True, db_index=True, default="", max_length=196, verbose_name="Auto_DB_Pro article key"),
        ),
        migrations.AddField(
            model_name="productfitment",
            name="autodb_passanger_car_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name="Auto_DB_Pro passanger_car ID"),
        ),
        migrations.AddField(
            model_name="productfitment",
            name="is_stale",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Устаревшая совместимость"),
        ),
        migrations.AddField(
            model_name="productfitment",
            name="linkage_type",
            field=models.CharField(blank=True, db_index=True, default="", max_length=32, verbose_name="Тип связи"),
        ),
        migrations.AddField(
            model_name="productfitment",
            name="manual_locked",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Совместимость закреплена вручную"),
        ),
        migrations.AddField(
            model_name="productfitment",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[("manual", "Manual"), ("autodb_pro", "Auto_DB_Pro"), ("legacy", "Legacy")],
                db_index=True,
                default="legacy",
                max_length=24,
                verbose_name="Источник",
            ),
        ),
        migrations.AddField(
            model_name="productfitment",
            name="source_hash",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64, verbose_name="Source hash"),
        ),
        migrations.AddField(
            model_name="productfitment",
            name="source_payload",
            field=models.JSONField(blank=True, default=dict, verbose_name="Source payload"),
        ),
        migrations.AddField(
            model_name="productfitment",
            name="stale_reason",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="Причина устаревания"),
        ),
        migrations.AddField(
            model_name="productfitment",
            name="supplier_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name="Auto_DB_Pro supplier ID"),
        ),
        migrations.AlterField(
            model_name="productfitment",
            name="modification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fitments",
                to="vehicles.vehiclemodification",
                verbose_name="Модификация",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="productfitment",
            name="compatibility_fitment_unique_product_modification",
        ),
        migrations.AddConstraint(
            model_name="productfitment",
            constraint=models.UniqueConstraint(
                condition=models.Q(modification__isnull=False),
                fields=("product", "modification"),
                name="compatibility_fitment_unique_product_modification",
            ),
        ),
        migrations.AddConstraint(
            model_name="productfitment",
            constraint=models.UniqueConstraint(
                condition=models.Q(autodb_passanger_car_id__isnull=False),
                fields=("product", "source", "linkage_type", "autodb_passanger_car_id"),
                name="compatibility_fitment_unique_autodb_linkage",
            ),
        ),
        migrations.AddConstraint(
            model_name="productfitment",
            constraint=models.UniqueConstraint(
                condition=~models.Q(source_hash=""),
                fields=("product", "source", "source_hash"),
                name="compatibility_fitment_unique_source_hash",
            ),
        ),
    ]
