# Generated by Django 6.0.4 on 2026-05-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compatibility", "0003_productfitment_autodb_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="productfitment",
            name="excluded_from_public_filtering",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Исключено из публичной фильтрации"),
        ),
        migrations.AddField(
            model_name="productfitment",
            name="quality_reason",
            field=models.CharField(blank=True, default="", max_length=512, verbose_name="Причина качества link"),
        ),
        migrations.AddField(
            model_name="productfitment",
            name="quality_status",
            field=models.CharField(
                blank=True,
                choices=[("trusted", "Trusted"), ("suspicious", "Suspicious"), ("needs_manual_review", "Needs manual review")],
                db_index=True,
                default="",
                max_length=32,
                verbose_name="Статус качества link",
            ),
        ),
    ]
