# Generated by Django 6.0.4 on 2026-05-31

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("compatibility", "0006_remove_legacy_vehicle_modification_fk"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="productfitment",
            index=models.Index(
                fields=["product", "autodb_passanger_car_id"],
                condition=Q(
                    source="autodb_pro",
                    is_stale=False,
                    excluded_from_public_filtering=False,
                    quality_status="trusted",
                    autodb_passanger_car_id__isnull=False,
                ),
                name="compat_fit_pub_prod_car_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productfitment",
            index=models.Index(
                fields=["product", "source", "autodb_passanger_car_id"],
                condition=Q(
                    is_stale=False,
                    excluded_from_public_filtering=False,
                    quality_status="trusted",
                    autodb_passanger_car_id__isnull=False,
                ),
                name="compat_fit_pub_prod_src_idx",
            ),
        ),
    ]
