# Generated by Django 6.0.4 on 2026-04-11 13:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual'), ('import', 'Import')], default='auto', max_length=16)),
                ('comment', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PriceOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('override_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('product__name',),
            },
        ),
        migrations.CreateModel(
            name='PricingPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('supplier', 'Supplier'), ('brand', 'Brand'), ('category', 'Category'), ('brand_category', 'Brand + Category')], default='global', max_length=32)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('percent_markup', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('fixed_markup', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('min_margin_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rounding_step', models.DecimalField(decimal_places=2, default=1, max_digits=7)),
                ('psychological_rounding', models.BooleanField(default=False)),
                ('lock_auto_recalc', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('priority', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('cost_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_to', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('percent_markup', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('fixed_markup', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ('policy', 'priority', 'cost_from'),
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('logistics_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('extra_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('landed_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('raw_sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('auto_calculation_locked', models.BooleanField(default=False)),
                ('recalculated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('product__name',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SupplierOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_sku', models.CharField(max_length=128)),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('logistics_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('extra_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_qty', models.IntegerField(default=0)),
                ('lead_time_days', models.PositiveSmallIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('supplier__name', 'product__name'),
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.CharField(max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=14)),
                ('effective_at', models.DateTimeField()),
                ('source', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ('-effective_at',),
                'constraints': [models.UniqueConstraint(fields=('base_currency', 'quote_currency', 'effective_at'), name='pricing_currencyrate_unique_pair_moment')],
            },
        ),
    ]
