# Generated by Django 6.0.4 on 2026-04-11 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_prices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='priceoverride',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_override', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='pricingpolicy',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pricing_policies', to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='pricingpolicy',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pricing_policies', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='pricing.pricingpolicy'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_prices', to='pricing.pricingpolicy'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_price', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='product_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='pricing.productprice'),
        ),
        migrations.AddField(
            model_name='pricingpolicy',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pricing_policies', to='pricing.supplier'),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_offers', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='supplieroffer',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='pricing.supplier'),
        ),
        migrations.AddConstraint(
            model_name='supplieroffer',
            constraint=models.UniqueConstraint(fields=('supplier', 'product', 'supplier_sku'), name='pricing_supplieroffer_unique_supplier_product_sku'),
        ),
    ]
