# Generated by Django 6.0.4 on 2026-04-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_preferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='priority',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='quality_score',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
