# Generated by Django 6.0.4 on 2026-04-12 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_attribute_options_alter_attributevalue_options_and_more'),
        ('pricing', '0003_supplier_is_preferred_supplier_priority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencyrate',
            options={'ordering': ('-effective_at',), 'verbose_name': 'Курс валюты', 'verbose_name_plural': 'Курсы валют'},
        ),
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ('-created_at',), 'verbose_name': 'История цены', 'verbose_name_plural': 'История цен'},
        ),
        migrations.AlterModelOptions(
            name='priceoverride',
            options={'ordering': ('product__name',), 'verbose_name': 'Переопределение цены', 'verbose_name_plural': 'Переопределения цен'},
        ),
        migrations.AlterModelOptions(
            name='pricingpolicy',
            options={'ordering': ('priority', 'name'), 'verbose_name': 'Политика ценообразования', 'verbose_name_plural': 'Политики ценообразования'},
        ),
        migrations.AlterModelOptions(
            name='pricingrule',
            options={'ordering': ('policy', 'priority', 'cost_from'), 'verbose_name': 'Правило ценообразования', 'verbose_name_plural': 'Правила ценообразования'},
        ),
        migrations.AlterModelOptions(
            name='productprice',
            options={'ordering': ('product__name',), 'verbose_name': 'Цена товара', 'verbose_name_plural': 'Цены товаров'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ('name',), 'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterModelOptions(
            name='supplieroffer',
            options={'ordering': ('supplier__name', 'product__name'), 'verbose_name': 'Оффер поставщика', 'verbose_name_plural': 'Офферы поставщиков'},
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='base_currency',
            field=models.CharField(max_length=3, verbose_name='Базовая валюта'),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='effective_at',
            field=models.DateTimeField(verbose_name='Действует с'),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='quote_currency',
            field=models.CharField(max_length=3, verbose_name='Котируемая валюта'),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=14, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='source',
            field=models.CharField(blank=True, max_length=64, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_prices', to=settings.AUTH_USER_MODEL, verbose_name='Кем изменено'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='new_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Новая цена'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='product_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='pricing.productprice', verbose_name='Текущая цена товара'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='source',
            field=models.CharField(choices=[('auto', 'Авто'), ('manual', 'Вручную'), ('import', 'Импорт')], default='auto', max_length=16, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='priceoverride',
            name='currency',
            field=models.CharField(default='UAH', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='priceoverride',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='priceoverride',
            name='override_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Переопределенная цена'),
        ),
        migrations.AlterField(
            model_name='priceoverride',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_override', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='priceoverride',
            name='reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='pricingpolicy',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pricing_policies', to='catalog.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='pricingpolicy',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pricing_policies', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='pricingpolicy',
            name='fixed_markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Фиксированная наценка'),
        ),
        migrations.AlterField(
            model_name='pricingpolicy',
            name='lock_auto_recalc',
            field=models.BooleanField(default=False, verbose_name='Запретить авто-перерасчет'),
        ),
        migrations.AlterField(
            model_name='pricingpolicy',
            name='min_margin_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Минимальная маржа, %'),
        ),
        migrations.AlterField(
            model_name='pricingpolicy',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Минимальная цена'),
        ),
        migrations.AlterField(
            model_name='pricingpolicy',
            name='name',
            field=models.CharField(max_length=180, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='pricingpolicy',
            name='percent_markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Процент наценки'),
        ),
        migrations.AlterField(
            model_name='pricingpolicy',
            name='priority',
            field=models.PositiveIntegerField(default=100, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='pricingpolicy',
            name='psychological_rounding',
            field=models.BooleanField(default=False, verbose_name='Психологическое округление'),
        ),
        migrations.AlterField(
            model_name='pricingpolicy',
            name='rounding_step',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Шаг округления'),
        ),
        migrations.AlterField(
            model_name='pricingpolicy',
            name='scope',
            field=models.CharField(choices=[('global', 'Глобально'), ('supplier', 'Поставщик'), ('brand', 'Бренд'), ('category', 'Категория'), ('brand_category', 'Бренд + категория')], default='global', max_length=32, verbose_name='Область действия'),
        ),
        migrations.AlterField(
            model_name='pricingpolicy',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pricing_policies', to='pricing.supplier', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='cost_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Себестоимость от'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='cost_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Себестоимость до'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='fixed_markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Фиксированная наценка'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='percent_markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Процент наценки'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='pricing.pricingpolicy', verbose_name='Политика'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='priority',
            field=models.PositiveIntegerField(default=100, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='auto_calculation_locked',
            field=models.BooleanField(default=False, verbose_name='Авторасчет заблокирован'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='currency',
            field=models.CharField(default='UAH', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='extra_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Дополнительные затраты'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Финальная цена'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='landed_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Себестоимость'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='logistics_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Логистика'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_prices', to='pricing.pricingpolicy', verbose_name='Политика'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_price', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Закупочная цена'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='raw_sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Базовая цена продажи'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='recalculated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Пересчитано'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.SlugField(max_length=64, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Контактный email'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_preferred',
            field=models.BooleanField(default=False, verbose_name='Предпочтительный'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=180, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='priority',
            field=models.PositiveIntegerField(default=100, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='quality_score',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Оценка качества'),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='currency',
            field=models.CharField(default='UAH', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='extra_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Дополнительные затраты'),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступен'),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='lead_time_days',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Срок поставки, дней'),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='logistics_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Логистика'),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_offers', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Закупочная цена'),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='stock_qty',
            field=models.IntegerField(default=0, verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='pricing.supplier', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='supplier_sku',
            field=models.CharField(max_length=128, verbose_name='SKU поставщика'),
        ),
    ]
