# Generated by Django 6.0.4 on 2026-04-12 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('vehicles', '0002_alter_vehicleengine_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garagevehicle',
            options={'ordering': ('-is_primary', '-created_at'), 'verbose_name': 'Автомобиль в гараже', 'verbose_name_plural': 'Гараж пользователей'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-date_joined',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='garagevehicle',
            name='engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='garage_vehicles', to='vehicles.vehicleengine', verbose_name='Двигатель'),
        ),
        migrations.AlterField(
            model_name='garagevehicle',
            name='generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='garage_vehicles', to='vehicles.vehiclegeneration', verbose_name='Поколение'),
        ),
        migrations.AlterField(
            model_name='garagevehicle',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
        migrations.AlterField(
            model_name='garagevehicle',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='garage_vehicles', to='vehicles.vehiclemake', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='garagevehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='garage_vehicles', to='vehicles.vehiclemodel', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='garagevehicle',
            name='modification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='garage_vehicles', to='vehicles.vehiclemodification', verbose_name='Модификация'),
        ),
        migrations.AlterField(
            model_name='garagevehicle',
            name='nickname',
            field=models.CharField(blank=True, max_length=120, verbose_name='Название в гараже'),
        ),
        migrations.AlterField(
            model_name='garagevehicle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='garagevehicle',
            name='vin',
            field=models.CharField(blank=True, max_length=32, verbose_name='VIN'),
        ),
        migrations.AlterField(
            model_name='garagevehicle',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('uk', 'Украинский'), ('ru', 'Русский'), ('en', 'Английский')], default='uk', max_length=2, verbose_name='Предпочитаемый язык'),
        ),
    ]
