# Generated by Django 6.0.4 on 2026-04-16 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("autocatalog", "0003_alter_carmodification_engine"),
        ("users", "0002_alter_garagevehicle_options_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="garagevehicle",
            name="make",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="garage_vehicles",
                to="vehicles.vehiclemake",
                verbose_name="Марка",
            ),
        ),
        migrations.AlterField(
            model_name="garagevehicle",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="garage_vehicles",
                to="vehicles.vehiclemodel",
                verbose_name="Модель",
            ),
        ),
        migrations.AddField(
            model_name="garagevehicle",
            name="car_modification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="garage_vehicles",
                to="autocatalog.carmodification",
                verbose_name="Автокаталог",
            ),
        ),
        migrations.AddConstraint(
            model_name="garagevehicle",
            constraint=models.UniqueConstraint(
                condition=models.Q(car_modification__isnull=False),
                fields=("user", "car_modification"),
                name="users_garage_unique_autocatalog_vehicle_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="garagevehicle",
            constraint=models.UniqueConstraint(
                condition=models.Q(is_primary=True),
                fields=("user",),
                name="users_garage_single_primary_vehicle_per_user",
            ),
        ),
    ]
