# Generated by Django 6.0.4 on 2026-04-21 09:57

import apps.users.models.user
from django.db import migrations
from django.db.models import F


def backfill_first_name_from_username(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(first_name="", username__isnull=False).exclude(username="").update(first_name=F("username"))


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_backoffice_user_card_edit_capabilities'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.models.user.UserManager()),
            ],
        ),
        migrations.RunPython(backfill_first_name_from_username, reverse_code=noop_reverse),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
