# Generated by Django 6.0.4 on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_checkout_methods_capability"),
    ]

    operations = [
        migrations.AddField(
            model_name="garagevehicle",
            name="autodb_manufacturer_id",
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name="Auto_DB_Pro manufacturer id"),
        ),
        migrations.AddField(
            model_name="garagevehicle",
            name="autodb_model_id",
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name="Auto_DB_Pro model id"),
        ),
        migrations.AddField(
            model_name="garagevehicle",
            name="autodb_passanger_car_id",
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name="Auto_DB_Pro passanger car id"),
        ),
        migrations.AddField(
            model_name="garagevehicle",
            name="autodb_vehicle_label",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Auto_DB_Pro vehicle label"),
        ),
        migrations.AddField(
            model_name="garagevehicle",
            name="catalog_source",
            field=models.CharField(
                choices=[("legacy", "Legacy"), ("autodb_pro", "Auto_DB_Pro")],
                db_index=True,
                default="legacy",
                max_length=24,
                verbose_name="Каталог-источник",
            ),
        ),
        migrations.AddConstraint(
            model_name="garagevehicle",
            constraint=models.UniqueConstraint(
                condition=models.Q(autodb_passanger_car_id__isnull=False),
                fields=("user", "autodb_passanger_car_id"),
                name="users_garage_unique_autodb_vehicle_per_user",
            ),
        ),
    ]
