# Generated by Django 6.0.4 on 2026-05-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_garagevehicle_autodb_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="garagevehicle",
            name="autodb_engine",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Auto_DB_Pro engine"),
        ),
        migrations.AddField(
            model_name="garagevehicle",
            name="autodb_modification",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Auto_DB_Pro modification"),
        ),
        migrations.AddField(
            model_name="garagevehicle",
            name="autodb_power_hp",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Auto_DB_Pro power HP"),
        ),
        migrations.AddField(
            model_name="garagevehicle",
            name="autodb_power_kw",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Auto_DB_Pro power kW"),
        ),
    ]
