# Generated by Django 6.0.4 on 2026-05-04 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodb', '0003_article_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoDbEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autodb_engine_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Auto-DB engine ID')),
                ('engine_code', models.CharField(blank=True, default='', max_length=128, verbose_name='Код двигателя')),
                ('capacity', models.CharField(blank=True, default='', max_length=64, verbose_name='Объем')),
                ('power_kw', models.IntegerField(blank=True, null=True, verbose_name='Мощность кВт')),
                ('power_hp', models.IntegerField(blank=True, null=True, verbose_name='Мощность л.с.')),
                ('fuel_type', models.CharField(blank=True, default='', max_length=64, verbose_name='Тип топлива')),
                ('source_payload', models.JSONField(blank=True, default=dict, verbose_name='Source payload')),
            ],
            options={
                'verbose_name': 'Двигатель Auto_DB_Pro',
                'verbose_name_plural': 'Двигатели Auto_DB_Pro',
                'db_table': 'autodb_pro_engines',
            },
        ),
        migrations.CreateModel(
            name='AutoDbSupplierBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autodb_supplier_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Auto-DB supplier ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Название')),
                ('normalized_name', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Нормализованное название')),
                ('supplier_details_payload', models.JSONField(blank=True, default=dict, verbose_name='Supplier details payload')),
                ('source_payload', models.JSONField(blank=True, default=dict, verbose_name='Source payload')),
            ],
            options={
                'verbose_name': 'Бренд поставщика Auto_DB_Pro',
                'verbose_name_plural': 'Бренды поставщиков Auto_DB_Pro',
                'db_table': 'autodb_pro_supplier_brands',
            },
        ),
        migrations.CreateModel(
            name='AutoDbSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=64, unique=True, verbose_name='Scope')),
                ('status', models.CharField(blank=True, default='', max_length=32, verbose_name='Status')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Состояние синхронизации Auto_DB_Pro',
                'verbose_name_plural': 'Состояния синхронизации Auto_DB_Pro',
                'db_table': 'autodb_pro_sync_state',
            },
        ),
        migrations.CreateModel(
            name='AutoDbVehicleManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autodb_manufacturer_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Auto-DB manufacturer ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Название')),
                ('normalized_name', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Нормализованное название')),
                ('country_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID страны')),
                ('source_payload', models.JSONField(blank=True, default=dict, verbose_name='Source payload')),
                ('source_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Обновлено в источнике')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Импортировано')),
            ],
            options={
                'verbose_name': 'Производитель авто Auto_DB_Pro',
                'verbose_name_plural': 'Производители авто Auto_DB_Pro',
                'db_table': 'autodb_pro_vehicle_manufacturers',
            },
        ),
        migrations.CreateModel(
            name='AutoDbPrd',
            fields=[
            ],
            options={
                'verbose_name': 'Группа товаров Auto_DB_Pro (PRD)',
                'verbose_name_plural': 'Группы товаров Auto_DB_Pro (PRD)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('autodb.autodbproductgroup',),
        ),
        migrations.AddField(
            model_name='autodbpassengercar',
            name='autodb_vehicle_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Auto-DB vehicle ID'),
        ),
        migrations.AddField(
            model_name='autodbpassengercar',
            name='body_type',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Тип кузова'),
        ),
        migrations.AddField(
            model_name='autodbpassengercar',
            name='engine_capacity',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Объем двигателя'),
        ),
        migrations.AddField(
            model_name='autodbpassengercar',
            name='engine_code',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Код двигателя'),
        ),
        migrations.AddField(
            model_name='autodbpassengercar',
            name='fuel_type',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Тип топлива'),
        ),
        migrations.AddField(
            model_name='autodbpassengercar',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Импортировано'),
        ),
        migrations.AddField(
            model_name='autodbpassengercar',
            name='ktype',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='KType'),
        ),
        migrations.AddField(
            model_name='autodbpassengercar',
            name='modification_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Модификация'),
        ),
        migrations.AddField(
            model_name='autodbpassengercar',
            name='power_hp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мощность л.с.'),
        ),
        migrations.AddField(
            model_name='autodbpassengercar',
            name='power_kw',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мощность кВт'),
        ),
        migrations.AddField(
            model_name='autodbpassengercar',
            name='source_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Source payload'),
        ),
        migrations.AddField(
            model_name='autodbpassengercar',
            name='source_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Обновлено в источнике'),
        ),
        migrations.AddField(
            model_name='autodbproductgroup',
            name='autodb_prd_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Auto-DB PRD ID'),
        ),
        migrations.AddField(
            model_name='autodbproductgroup',
            name='category_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Category ID'),
        ),
        migrations.AddField(
            model_name='autodbproductgroup',
            name='group_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Group ID'),
        ),
        migrations.AddField(
            model_name='autodbproductgroup',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='autodbproductgroup',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название (RU)'),
        ),
        migrations.AddField(
            model_name='autodbproductgroup',
            name='name_uk',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название (UA)'),
        ),
        migrations.AddField(
            model_name='autodbproductgroup',
            name='parent_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Parent ID'),
        ),
        migrations.AddField(
            model_name='autodbproductgroup',
            name='source_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Source payload'),
        ),
        migrations.AddField(
            model_name='autodbvehiclemodel',
            name='autodb_model_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Auto-DB model ID'),
        ),
        migrations.AddField(
            model_name='autodbvehiclemodel',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Импортировано'),
        ),
        migrations.AddField(
            model_name='autodbvehiclemodel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='autodbvehiclemodel',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Нормализованное название'),
        ),
        migrations.AddField(
            model_name='autodbvehiclemodel',
            name='source_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Source payload'),
        ),
        migrations.AddField(
            model_name='autodbvehiclemodel',
            name='source_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Обновлено в источнике'),
        ),
        migrations.AddField(
            model_name='autodbvehiclemodel',
            name='year_from',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год от'),
        ),
        migrations.AddField(
            model_name='autodbvehiclemodel',
            name='year_to',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год до'),
        ),
        migrations.CreateModel(
            name='AutoDbPassengerCarEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_id', models.BigIntegerField(blank=True, null=True, verbose_name='Engine ID')),
                ('engine_code', models.CharField(blank=True, default='', max_length=128, verbose_name='Код двигателя')),
                ('capacity', models.CharField(blank=True, default='', max_length=64, verbose_name='Объем')),
                ('power_kw', models.IntegerField(blank=True, null=True, verbose_name='Мощность кВт')),
                ('power_hp', models.IntegerField(blank=True, null=True, verbose_name='Мощность л.с.')),
                ('fuel_type', models.CharField(blank=True, default='', max_length=64, verbose_name='Тип топлива')),
                ('source_payload', models.JSONField(blank=True, default=dict, verbose_name='Source payload')),
                ('passenger_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engines', to='autodb.autodbpassengercar')),
            ],
            options={
                'verbose_name': 'Двигатель модификации Auto_DB_Pro',
                'verbose_name_plural': 'Двигатели модификаций Auto_DB_Pro',
                'db_table': 'autodb_pro_passenger_car_engines',
            },
        ),
        migrations.CreateModel(
            name='AutoDbPassengerCarTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='PRD ID')),
                ('category_id', models.BigIntegerField(blank=True, null=True, verbose_name='Category ID')),
                ('parent_id', models.BigIntegerField(blank=True, null=True, verbose_name='Parent ID')),
                ('name_uk', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (UA)')),
                ('name_ru', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (RU)')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (EN)')),
                ('source_payload', models.JSONField(blank=True, default=dict, verbose_name='Source payload')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='autodb.autodbpassengercar')),
            ],
            options={
                'verbose_name': 'Дерево легковых авто Auto_DB_Pro',
                'verbose_name_plural': 'Деревья легковых авто Auto_DB_Pro',
                'db_table': 'autodb_pro_passenger_car_trees',
            },
        ),
        migrations.CreateModel(
            name='AutoDbVehicleAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(blank=True, default='', max_length=128, verbose_name='Source key')),
                ('name_uk', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (UA)')),
                ('name_ru', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (RU)')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (EN)')),
                ('value_uk', models.CharField(blank=True, default='', max_length=255, verbose_name='Значение (UA)')),
                ('value_ru', models.CharField(blank=True, default='', max_length=255, verbose_name='Значение (RU)')),
                ('value_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Значение (EN)')),
                ('unit', models.CharField(blank=True, default='', max_length=64, verbose_name='Единица')),
                ('source_payload', models.JSONField(blank=True, default=dict, verbose_name='Source payload')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='autodb.autodbpassengercar')),
            ],
            options={
                'verbose_name': 'Атрибут авто Auto_DB_Pro',
                'verbose_name_plural': 'Атрибуты авто Auto_DB_Pro',
                'db_table': 'autodb_pro_vehicle_attributes',
            },
        ),
        migrations.AddField(
            model_name='autodbpassengercar',
            name='vehicle_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger_cars', to='autodb.autodbvehiclemanufacturer'),
        ),
        migrations.AddField(
            model_name='autodbvehiclemodel',
            name='vehicle_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_models', to='autodb.autodbvehiclemanufacturer'),
        ),
        migrations.AddIndex(
            model_name='autodbpassengercar',
            index=models.Index(fields=['ktype'], name='adb_pro_pc_ktype_idx'),
        ),
        migrations.AddIndex(
            model_name='autodbvehiclemodel',
            index=models.Index(fields=['normalized_name'], name='adb_pro_model_nname_idx'),
        ),
        migrations.AddIndex(
            model_name='autodbpassengercarengine',
            index=models.Index(fields=['passenger_car'], name='adb_pro_pce_car_idx'),
        ),
        migrations.AddIndex(
            model_name='autodbpassengercarengine',
            index=models.Index(fields=['engine_id'], name='adb_pro_pce_engine_idx'),
        ),
        migrations.AddIndex(
            model_name='autodbpassengercartree',
            index=models.Index(fields=['vehicle'], name='adb_pro_pctree_vehicle_idx'),
        ),
        migrations.AddIndex(
            model_name='autodbpassengercartree',
            index=models.Index(fields=['prd_id'], name='adb_pro_pctree_prd_idx'),
        ),
        migrations.AddIndex(
            model_name='autodbvehicleattribute',
            index=models.Index(fields=['vehicle'], name='adb_pro_vattr_vehicle_idx'),
        ),
        migrations.AddIndex(
            model_name='autodbvehicleattribute',
            index=models.Index(fields=['source_key'], name='adb_pro_vattr_key_idx'),
        ),
    ]
