# Generated by Django 6.0.4 on 2026-05-12 12:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodb', '0007_autodbsupplierbrandalias'),
        ('catalog', '0025_product_views_count'),
        ('pricing', '0009_supplieroffer_price_levels_db_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoDbMatchingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_type', models.CharField(db_index=True, max_length=64, verbose_name='Run type')),
                ('status', models.CharField(choices=[('running', 'running'), ('success', 'success'), ('failed', 'failed'), ('partial', 'partial')], db_index=True, default='running', max_length=24, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finished at')),
                ('dry_run', models.BooleanField(db_index=True, default=True, verbose_name='Dry run')),
                ('created_by_source', models.CharField(blank=True, default='', max_length=128, verbose_name='Created by/source')),
                ('summary_json', models.JSONField(blank=True, default=dict, verbose_name='Summary')),
                ('error', models.TextField(blank=True, default='', verbose_name='Error')),
            ],
            options={
                'verbose_name': 'Auto_DB matching run',
                'verbose_name_plural': 'Auto_DB matching runs',
                'db_table': 'autodb_matching_runs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['run_type', 'status'], name='autodb_match_run_type_stat_idx'), models.Index(fields=['-created_at'], name='autodb_match_run_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='AutoDbMatchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_code', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Supplier code')),
                ('raw_brand', models.CharField(blank=True, default='', max_length=255, verbose_name='Raw brand')),
                ('normalized_brand', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Normalized brand')),
                ('resolved_supplier_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Auto_DB supplier ID')),
                ('article_source_type', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Article source type')),
                ('article_value', models.CharField(blank=True, default='', max_length=128, verbose_name='Article value')),
                ('canonical_article', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='Canonical article')),
                ('status', models.CharField(choices=[('new', 'new'), ('skipped_non_tecdoc', 'skipped_non_tecdoc'), ('skipped_brand_unresolved', 'skipped_brand_unresolved'), ('skipped_split_needed', 'skipped_split_needed'), ('skipped_unsafe_ambiguous', 'skipped_unsafe_ambiguous'), ('skipped_bad_article_source', 'skipped_bad_article_source'), ('local_found', 'local_found'), ('remote_pending', 'remote_pending'), ('remote_found', 'remote_found'), ('remote_not_found', 'remote_not_found'), ('quota_paused', 'quota_paused'), ('clone_sync_ready', 'clone_sync_ready'), ('clone_synced', 'clone_synced'), ('safe_link_candidate', 'safe_link_candidate'), ('linked', 'linked'), ('needs_review', 'needs_review'), ('rejected', 'rejected')], db_index=True, default='new', max_length=48, verbose_name='Status')),
                ('priority', models.PositiveSmallIntegerField(db_index=True, default=100, verbose_name='Priority')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='Attempt count')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Last error')),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Next retry at')),
                ('metadata_json', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='autodb.autodbmatchingrun', verbose_name='Last run')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autodb_match_jobs', to='catalog.product', verbose_name='Product')),
                ('supplier_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autodb_match_jobs', to='pricing.supplieroffer', verbose_name='Supplier offer')),
            ],
            options={
                'verbose_name': 'Auto_DB match job',
                'verbose_name_plural': 'Auto_DB match jobs',
                'db_table': 'autodb_match_jobs',
                'ordering': ('priority', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='AutoDbMatchEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(db_index=True, max_length=64, verbose_name='Stage')),
                ('source', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Source')),
                ('result', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Result')),
                ('supplier_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Auto_DB supplier ID')),
                ('article_value', models.CharField(blank=True, default='', max_length=128, verbose_name='Article value')),
                ('canonical_article', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='Canonical article')),
                ('remote_stored_article', models.CharField(blank=True, default='', max_length=128, verbose_name='Remote stored article')),
                ('article_prd_present', models.BooleanField(default=False, verbose_name='article_prd present')),
                ('prd_present', models.BooleanField(default=False, verbose_name='prd present')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Reason')),
                ('payload_json', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='autodb.autodbmatchjob', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Auto_DB match evidence',
                'verbose_name_plural': 'Auto_DB match evidence',
                'db_table': 'autodb_match_evidence',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AutoDbRemoteQuotaState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_key', models.CharField(max_length=128, unique=True, verbose_name='Remote key')),
                ('last_ok_at', models.DateTimeField(blank=True, null=True, verbose_name='Last OK at')),
                ('last_quota_error_at', models.DateTimeField(blank=True, null=True, verbose_name='Last quota error at')),
                ('estimated_queries_used', models.PositiveIntegerField(default=0, verbose_name='Estimated queries used')),
                ('cooldown_until', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Cooldown until')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Last error')),
            ],
            options={
                'verbose_name': 'Auto_DB remote quota state',
                'verbose_name_plural': 'Auto_DB remote quota states',
                'db_table': 'autodb_remote_quota_states',
                'ordering': ('remote_key',),
                'indexes': [models.Index(fields=['remote_key', 'cooldown_until'], name='autodb_quota_key_cool_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='autodbmatchjob',
            index=models.Index(fields=['status', 'priority'], name='autodb_match_job_status_pr_idx'),
        ),
        migrations.AddIndex(
            model_name='autodbmatchjob',
            index=models.Index(fields=['supplier_code', 'status'], name='autodb_match_job_sup_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='autodbmatchjob',
            index=models.Index(fields=['resolved_supplier_id', 'canonical_article'], name='autodb_match_job_supp_art_idx'),
        ),
        migrations.AddIndex(
            model_name='autodbmatchjob',
            index=models.Index(fields=['product', 'status'], name='autodb_match_job_prod_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='autodbmatchevidence',
            index=models.Index(fields=['job', 'stage'], name='autodb_match_ev_job_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='autodbmatchevidence',
            index=models.Index(fields=['stage', 'result'], name='autodb_match_ev_stage_res_idx'),
        ),
    ]
