# Generated by Django 6.0.4 on 2026-05-19 09:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_telegram_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnServiceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default='default', max_length=32, unique=True, verbose_name='Код профиля')),
                ('returns_enabled', models.BooleanField(default=False, verbose_name='Сервис возвратов включен')),
                ('returns_recipient_full_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Получатель ФИО')),
                ('returns_recipient_phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Получатель телефон')),
                ('returns_region_ref', models.CharField(blank=True, default='', max_length=64, verbose_name='Ref области')),
                ('returns_region_label', models.CharField(blank=True, default='', max_length=255, verbose_name='Область')),
                ('returns_city_ref', models.CharField(blank=True, default='', max_length=64, verbose_name='Ref города')),
                ('returns_city_label', models.CharField(blank=True, default='', max_length=255, verbose_name='Город')),
                ('returns_np_warehouse_text', models.CharField(blank=True, default='', max_length=255, verbose_name='Отделение Новой Почты')),
                ('returns_non_returnable_category_ids', models.JSONField(blank=True, default=list, verbose_name='Невозвратные категории')),
                ('returns_include_subcategories', models.BooleanField(default=True, verbose_name='Включать подкатегории')),
            ],
            options={
                'verbose_name': 'Настройки сервиса возвратов',
                'verbose_name_plural': 'Настройки сервиса возвратов',
            },
        ),
    ]
