# Generated by Django 6.0.4 on 2026-05-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_telegram_settings_returns_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsettings',
            name='system_notify_autodb_batch_status',
            field=models.BooleanField(default=True, verbose_name='System: AutoDB batch'),
        ),
    ]
