# Generated by Django 6.0.4 on 2026-04-13 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Марка')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('normalized_name', models.CharField(editable=False, max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Марка авто',
                'verbose_name_plural': 'Марки авто',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Модель')),
                ('slug', models.SlugField(max_length=140, verbose_name='Slug')),
                ('normalized_name', models.CharField(editable=False, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='autocatalog.carmake', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Модель авто',
                'verbose_name_plural': 'Модели авто',
                'ordering': ('make__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CarModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_at', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Год')),
                ('modification', models.CharField(blank=True, default='', max_length=255, verbose_name='Модификация')),
                ('capacity', models.CharField(blank=True, default='', max_length=32, verbose_name='Объем')),
                ('engine', models.CharField(blank=True, default='', max_length=120, verbose_name='Двигатель')),
                ('hp_from', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Мощность HP')),
                ('kw_from', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Мощность KW')),
                ('dedupe_key', models.CharField(editable=False, max_length=160, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='autocatalog.carmake', verbose_name='Марка')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='autocatalog.carmodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Авто в каталоге',
                'verbose_name_plural': 'Автокаталог',
                'ordering': ('-year', 'make__name', 'model__name', 'modification'),
            },
        ),
        migrations.CreateModel(
            name='UtrDetailCarMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utr_detail_id', models.CharField(max_length=64, verbose_name='UTR detail ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('car_modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utr_detail_maps', to='autocatalog.carmodification', verbose_name='Авто')),
            ],
            options={
                'verbose_name': 'Связь UTR детали с авто',
                'verbose_name_plural': 'Связи UTR деталей с авто',
                'ordering': ('utr_detail_id', 'car_modification_id'),
            },
        ),
        migrations.AddConstraint(
            model_name='carmodel',
            constraint=models.UniqueConstraint(fields=('make', 'normalized_name'), name='autocatalog_model_unique_name_per_make'),
        ),
        migrations.AddConstraint(
            model_name='carmodel',
            constraint=models.UniqueConstraint(fields=('make', 'slug'), name='autocatalog_model_unique_slug_per_make'),
        ),
        migrations.AddIndex(
            model_name='utrdetailcarmap',
            index=models.Index(fields=['utr_detail_id'], name='autocatalog_utr_detail_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='utrdetailcarmap',
            constraint=models.UniqueConstraint(fields=('utr_detail_id', 'car_modification'), name='autocatalog_unique_utr_detail_car_modification'),
        ),
    ]
