# Generated by Codex on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autocatalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UtrArticleDetailMap",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("article", models.CharField(max_length=128, verbose_name="Артикул UTR")),
                ("normalized_article", models.CharField(db_index=True, max_length=128, verbose_name="Нормализованный артикул UTR")),
                ("brand_name", models.CharField(blank=True, max_length=180, verbose_name="Бренд")),
                ("normalized_brand", models.CharField(blank=True, db_index=True, max_length=180, verbose_name="Нормализованный бренд")),
                ("utr_detail_id", models.CharField(db_index=True, max_length=64, verbose_name="UTR detail ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
            ],
            options={
                "verbose_name": "Связь артикула UTR с detail ID",
                "verbose_name_plural": "Связи артикула UTR с detail ID",
                "ordering": ("normalized_article", "normalized_brand"),
            },
        ),
        migrations.AddIndex(
            model_name="utrarticledetailmap",
            index=models.Index(fields=["utr_detail_id"], name="ac_utr_article_did_idx"),
        ),
        migrations.AddConstraint(
            model_name="utrarticledetailmap",
            constraint=models.UniqueConstraint(
                fields=("normalized_article", "normalized_brand"),
                name="autocatalog_unique_utr_article_brand_detail_map",
            ),
        ),
    ]
