# Generated by Django 6.0.4 on 2026-04-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocatalog', '0002_utrarticledetailmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodification',
            name='engine',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Двигатель'),
        ),
    ]
