# Generated by Django 6.0.4 on 2026-04-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autocatalog", "0003_alter_carmodification_engine"),
    ]

    operations = [
        migrations.AddField(
            model_name="carmodification",
            name="end_date_at",
            field=models.DateField(blank=True, null=True, verbose_name="Дата окончания"),
        ),
    ]
