# Generated by Django 6.0.4 on 2026-05-10 10:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('endpoint_pattern', models.CharField(blank=True, default='', max_length=255, verbose_name='Endpoint pattern')),
                ('scope', models.CharField(blank=True, default='', max_length=64, verbose_name='Scope')),
                ('limit', models.PositiveIntegerField(default=0, verbose_name='Limit')),
                ('window_seconds', models.PositiveIntegerField(default=60, verbose_name='Window seconds')),
                ('action', models.CharField(blank=True, default='', max_length=64, verbose_name='Action')),
                ('enabled', models.BooleanField(db_index=True, default=True, verbose_name='Enabled')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Priority')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Security rule',
                'verbose_name_plural': 'Security rules',
                'ordering': ('priority', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SecurityActor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='Source IP')),
                ('source_identifier', models.CharField(db_index=True, max_length=255, verbose_name='Source identifier')),
                ('source_kind', models.CharField(choices=[('ipv4', 'IPv4'), ('ipv6', 'IPv6'), ('unknown', 'Unknown')], default='unknown', max_length=24, verbose_name='Source kind')),
                ('login_snapshot', models.CharField(blank=True, default='', max_length=255, verbose_name='Login snapshot')),
                ('email_snapshot', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email snapshot')),
                ('threat_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=16, verbose_name='Threat level')),
                ('threat_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Threat score')),
                ('status', models.CharField(choices=[('suspicious', 'Suspicious'), ('blocked', 'Blocked'), ('whitelisted', 'Whitelisted'), ('unblocked', 'Unblocked'), ('expired', 'Expired'), ('error', 'Error')], db_index=True, default='suspicious', max_length=24, verbose_name='Status')),
                ('block_count', models.PositiveIntegerField(default=0, verbose_name='Block count')),
                ('first_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='First seen at')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Last seen at')),
                ('last_blocked_at', models.DateTimeField(blank=True, null=True, verbose_name='Last blocked at')),
                ('last_unblocked_at', models.DateTimeField(blank=True, null=True, verbose_name='Last unblocked at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_actors', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Security actor',
                'verbose_name_plural': 'Security actors',
                'ordering': ('-last_seen_at', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('action', models.CharField(db_index=True, max_length=64, verbose_name='Action')),
                ('target_type', models.CharField(db_index=True, max_length=64, verbose_name='Target type')),
                ('target_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Target ID')),
                ('target_label', models.CharField(blank=True, default='', max_length=255, verbose_name='Target label')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Old value')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='New value')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User agent')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Admin user')),
            ],
            options={
                'verbose_name': 'Security audit log',
                'verbose_name_plural': 'Security audit logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SecurityBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_type', models.CharField(choices=[('ip', 'IP'), ('account', 'Account'), ('user_agent', 'User agent'), ('fingerprint', 'Fingerprint'), ('subnet', 'Subnet')], default='ip', max_length=24, verbose_name='Block type')),
                ('value', models.CharField(db_index=True, max_length=255, verbose_name='Value')),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('expired', 'Expired')], db_index=True, default='active', max_length=16, verbose_name='Status')),
                ('reason', models.TextField(blank=True, verbose_name='Reason')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('is_automatic', models.BooleanField(default=True, verbose_name='Automatic')),
                ('blocked_at', models.DateTimeField(verbose_name='Blocked at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires at')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='Released at')),
                ('release_reason', models.TextField(blank=True, verbose_name='Release reason')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='security.securityactor', verbose_name='Actor')),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_blocks_created', to=settings.AUTH_USER_MODEL, verbose_name='Blocked by')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_blocks_released', to=settings.AUTH_USER_MODEL, verbose_name='Released by')),
            ],
            options={
                'verbose_name': 'Security block',
                'verbose_name_plural': 'Security blocks',
                'ordering': ('-blocked_at',),
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('event_type', models.CharField(db_index=True, max_length=64, verbose_name='Event type')),
                ('severity', models.CharField(blank=True, db_index=True, default='', max_length=16, verbose_name='Severity')),
                ('source_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='Source IP')),
                ('source_kind', models.CharField(blank=True, default='', max_length=24, verbose_name='Source kind')),
                ('login_snapshot', models.CharField(blank=True, default='', max_length=255, verbose_name='Login snapshot')),
                ('email_snapshot', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email snapshot')),
                ('method', models.CharField(blank=True, default='', max_length=16, verbose_name='Method')),
                ('endpoint', models.CharField(blank=True, default='', max_length=512, verbose_name='Endpoint')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Status code')),
                ('user_agent', models.TextField(blank=True, verbose_name='User agent')),
                ('fingerprint', models.CharField(blank=True, default='', max_length=255, verbose_name='Fingerprint')),
                ('session_key', models.CharField(blank=True, default='', max_length=255, verbose_name='Session key')),
                ('rule', models.CharField(blank=True, default='', max_length=255, verbose_name='Rule')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('actor_type', models.CharField(choices=[('system', 'System'), ('admin', 'Admin'), ('user', 'User'), ('anonymous', 'Anonymous')], default='system', max_length=16, verbose_name='Actor type')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='security.securityactor')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events_as_actor', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security event',
                'verbose_name_plural': 'Security events',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SecuritySetting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='Key')),
                ('value', models.JSONField(blank=True, default=dict, verbose_name='Value')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security setting',
                'verbose_name_plural': 'Security settings',
                'ordering': ('key',),
            },
        ),
        migrations.AddIndex(
            model_name='securityactor',
            index=models.Index(fields=['status', 'threat_level'], name='sec_actor_status_threat_idx'),
        ),
        migrations.AddIndex(
            model_name='securityactor',
            index=models.Index(fields=['last_seen_at'], name='sec_actor_last_seen_idx'),
        ),
        migrations.AddConstraint(
            model_name='securityactor',
            constraint=models.UniqueConstraint(fields=('source_identifier',), name='security_actor_source_identifier_uniq'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['target_type', 'target_id'], name='sec_audit_target_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['action', 'created_at'], name='sec_audit_action_created_idx'),
        ),
        migrations.AddIndex(
            model_name='securityblock',
            index=models.Index(fields=['actor', 'status'], name='sec_block_actor_status_idx'),
        ),
        migrations.AddIndex(
            model_name='securityblock',
            index=models.Index(fields=['status', 'expires_at'], name='sec_block_status_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['actor', 'created_at'], name='sec_event_actor_created_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'created_at'], name='sec_event_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['source_ip', 'created_at'], name='sec_event_ip_created_idx'),
        ),
    ]
