# Generated by Codex on 2026-04-13

from django.db import migrations, models


def backfill_category_i18n(apps, schema_editor):
    Category = apps.get_model("catalog", "Category")
    for category in Category.objects.all().iterator(chunk_size=500):
        changed = []
        if not category.name_uk:
            category.name_uk = category.name
            changed.append("name_uk")
        if not category.name_ru:
            category.name_ru = category.name
            changed.append("name_ru")
        if not category.name_en:
            category.name_en = category.name
            changed.append("name_en")
        if changed:
            category.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_attribute_options_alter_attributevalue_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(blank=True, default="", max_length=180, verbose_name="Название (EN)"),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(blank=True, default="", max_length=180, verbose_name="Название (RU)"),
        ),
        migrations.AddField(
            model_name="category",
            name="name_uk",
            field=models.CharField(blank=True, default="", max_length=180, verbose_name="Название (UA)"),
        ),
        migrations.RunPython(backfill_category_i18n, migrations.RunPython.noop),
    ]
