# Generated by Django 6.0.4 on 2026-04-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_i18n_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='utr_detail_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='UTR detail ID'),
        ),
    ]
