# Generated by Codex on 2026-04-13

from django.db import migrations


def _extract_utr_detail_id(raw_payload) -> str:
    if not isinstance(raw_payload, dict):
        return ""
    if not isinstance(raw_payload.get("brand"), dict):
        return ""
    value = str(raw_payload.get("id") or "").strip()
    if not value.isdigit():
        return ""
    return value


def backfill_product_utr_detail_id(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    SupplierRawOffer = apps.get_model("supplier_imports", "SupplierRawOffer")

    queryset = (
        SupplierRawOffer.objects.filter(source__code="utr", matched_product__isnull=False)
        .select_related("matched_product")
        .order_by("-created_at")
    )

    for raw_offer in queryset.iterator(chunk_size=500):
        product = raw_offer.matched_product
        if product is None or product.utr_detail_id:
            continue

        utr_detail_id = _extract_utr_detail_id(raw_offer.raw_payload)
        if not utr_detail_id:
            continue

        Product.objects.filter(pk=product.pk, utr_detail_id="").update(utr_detail_id=utr_detail_id)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_utr_detail_id"),
        ("supplier_imports", "0007_supplierpricelist"),
    ]

    operations = [
        migrations.RunPython(backfill_product_utr_detail_id, migrations.RunPython.noop),
    ]
