# Generated by Codex on 2026-04-26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_backfill_product_utr_detail_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="UtrProductEnrichment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("utr_detail_id", models.CharField(blank=True, db_index=True, max_length=64, verbose_name="UTR detail ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("queued", "В очереди"),
                            ("in_progress", "Выполняется"),
                            ("fetched", "Получено"),
                            ("failed", "Ошибка"),
                            ("unavailable", "Недоступно"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=24,
                        verbose_name="Статус",
                    ),
                ),
                ("detail_payload", models.JSONField(blank=True, default=dict, verbose_name="UTR detail payload")),
                ("characteristics_payload", models.JSONField(blank=True, default=list, verbose_name="UTR characteristics payload")),
                ("images_payload", models.JSONField(blank=True, default=list, verbose_name="UTR images payload")),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True, verbose_name="Последняя попытка")),
                ("fetched_at", models.DateTimeField(blank=True, null=True, verbose_name="Получено")),
                ("next_retry_at", models.DateTimeField(blank=True, null=True, verbose_name="Следующая попытка")),
                ("error_message", models.TextField(blank=True, verbose_name="Текст ошибки")),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utr_enrichment",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "UTR обогащение товара",
                "verbose_name_plural": "UTR обогащения товаров",
                "ordering": ("product__name",),
            },
        ),
        migrations.AddIndex(
            model_name="utrproductenrichment",
            index=models.Index(fields=["status", "next_retry_at"], name="cat_utr_enrich_retry_idx"),
        ),
        migrations.AddIndex(
            model_name="utrproductenrichment",
            index=models.Index(fields=["utr_detail_id"], name="cat_utr_enrich_did_idx"),
        ),
    ]
