# Generated by Django 6.0.4 on 2026-05-05 06:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_name_enrichment_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoDbArticleManualMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(blank=True, default='', max_length=180, verbose_name='Бренд')),
                ('article', models.CharField(max_length=128, verbose_name='Артикул')),
                ('normalized_brand', models.CharField(db_index=True, max_length=180, verbose_name='Нормализованный бренд')),
                ('normalized_article', models.CharField(db_index=True, max_length=128, verbose_name='Нормализованный артикул')),
                ('autodb_supplier_id', models.BigIntegerField(db_index=True, verbose_name='Auto_DB_Pro supplier ID')),
                ('autodb_article_id', models.BigIntegerField(blank=True, null=True, verbose_name='Auto_DB_Pro article ID')),
                ('autodb_article_number', models.CharField(max_length=128, verbose_name='Auto_DB_Pro article number')),
                ('autodb_article_key', models.CharField(max_length=196, verbose_name='Auto_DB_Pro article key')),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='Уверенность')),
                ('manual_confirmed', models.BooleanField(db_index=True, default=False, verbose_name='Подтверждено вручную')),
                ('source', models.CharField(blank=True, default='manual', max_length=64, verbose_name='Источник')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Примечание')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autodb_manual_mappings', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
            ],
            options={
                'verbose_name': 'Ручной маппинг Auto_DB_Pro',
                'verbose_name_plural': 'Ручные маппинги Auto_DB_Pro',
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['normalized_brand', 'normalized_article', 'manual_confirmed'], name='cat_adb_manual_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('normalized_brand', 'normalized_article', 'autodb_article_key'), name='cat_adb_manual_map_unique')],
            },
        ),
    ]
