# Generated by Django 6.0.4 on 2026-05-05

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_product_image_sources_and_remote"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoDbProductLinkQuality",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("autodb_article_key", models.CharField(db_index=True, max_length=196, verbose_name="Auto_DB_Pro article key")),
                ("autodb_supplier_id", models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name="Auto_DB_Pro supplier ID")),
                (
                    "autodb_article_number",
                    models.CharField(blank=True, db_index=True, default="", max_length=128, verbose_name="Auto_DB_Pro article number"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("trusted", "Trusted"), ("suspicious", "Suspicious"), ("needs_manual_review", "Needs manual review")],
                        db_index=True,
                        max_length=32,
                        verbose_name="Статус качества link",
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=512, verbose_name="Причина")),
                ("evidence", models.JSONField(blank=True, default=dict, verbose_name="Доказательства")),
                ("checked_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Проверено")),
                ("manually_confirmed", models.BooleanField(db_index=True, default=False, verbose_name="Подтверждено вручную")),
                ("note", models.CharField(blank=True, default="", max_length=255, verbose_name="Примечание")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autodb_link_qualities",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Качество link Auto_DB_Pro",
                "verbose_name_plural": "Качество links Auto_DB_Pro",
                "ordering": ("-checked_at", "-updated_at"),
                "indexes": [
                    models.Index(fields=["status", "manually_confirmed"], name="cat_adb_link_q_stat_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="autodbproductlinkquality",
            constraint=models.UniqueConstraint(
                fields=("product", "autodb_article_key"),
                name="cat_adb_link_q_prod_key",
            ),
        ),
    ]
