# Generated by Django 6.0.4 on 2026-04-12 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
        ('pricing', '0003_supplier_is_preferred_supplier_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='last_known_availability_status',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='last_known_currency',
            field=models.CharField(default='UAH', max_length=3),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='last_known_estimated_delivery_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='last_known_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason_code',
            field=models.CharField(blank=True, choices=[('customer_request', 'Customer request'), ('payment_failed', 'Payment failed'), ('supplier_shortage', 'Supplier shortage'), ('unavailable', 'Unavailable'), ('operator_decision', 'Operator decision'), ('other', 'Other')], max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='operator_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='operator_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='procurement_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_procurement', 'Awaiting procurement'), ('reserved', 'Reserved'), ('partially_reserved', 'Partially reserved'), ('unavailable', 'Unavailable'), ('cancelled', 'Cancelled')], default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='recommended_supplier_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_for_order_items', to='pricing.supplieroffer'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_supplier_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_order_items', to='pricing.supplieroffer'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shortage_reason_code',
            field=models.CharField(blank=True, choices=[('stock_shortage', 'Stock shortage'), ('price_changed', 'Price changed'), ('supplier_unavailable', 'Supplier unavailable'), ('lead_time_too_long', 'Lead time too long'), ('other', 'Other')], max_length=32),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shortage_reason_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='snapshot_availability_label',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='snapshot_availability_status',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='snapshot_currency',
            field=models.CharField(default='UAH', max_length=3),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='snapshot_estimated_delivery_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='snapshot_offer_explainability',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='snapshot_procurement_source',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='snapshot_selected_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_for_order_items', to='pricing.supplieroffer'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='snapshot_sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('awaiting_procurement', 'Awaiting procurement'), ('reserved', 'Reserved'), ('partially_reserved', 'Partially reserved'), ('ready_to_ship', 'Ready to ship'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('draft', 'Draft (legacy)'), ('placed', 'Placed (legacy)')], default='new', max_length=32),
        ),
    ]
