# Generated by Django 6.0.4 on 2026-04-12 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_attribute_options_alter_attributevalue_options_and_more'),
        ('commerce', '0002_cartitem_last_known_availability_status_and_more'),
        ('pricing', '0004_alter_currencyrate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-updated_at',), 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ('created_at',), 'verbose_name': 'Позиция корзины', 'verbose_name_plural': 'Позиции корзины'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-placed_at', '-created_at'), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('created_at',), 'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Позиции заказа'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ('-created_at',), 'verbose_name': 'Элемент избранного', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='currency',
            field=models.CharField(default='UAH', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='last_known_availability_status',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Последний статус доступности'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='last_known_currency',
            field=models.CharField(default='UAH', max_length=3, verbose_name='Последняя валюта'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='last_known_estimated_delivery_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Последний срок доставки, дней'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='last_known_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Последняя цена за единицу'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancellation_reason_code',
            field=models.CharField(blank=True, choices=[('customer_request', 'Запрос клиента'), ('payment_failed', 'Ошибка оплаты'), ('supplier_shortage', 'Дефицит у поставщика'), ('unavailable', 'Недоступно'), ('operator_decision', 'Решение оператора'), ('other', 'Другое')], max_length=32, verbose_name='Причина отмены'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancellation_reason_note',
            field=models.TextField(blank=True, verbose_name='Комментарий к отмене'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_phone',
            field=models.CharField(max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='UAH', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Самовывоз'), ('courier', 'Курьер'), ('nova_poshta', 'Новая Почта')], max_length=32, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='internal_notes',
            field=models.TextField(blank=True, verbose_name='Внутренние заметки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='operator_notes',
            field=models.TextField(blank=True, verbose_name='Заметки оператора'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=32, unique=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Наложенный платеж'), ('card_placeholder', 'Оплата картой (placeholder)')], max_length=32, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='placed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('awaiting_procurement', 'Ожидает закупки'), ('reserved', 'Зарезервирован'), ('partially_reserved', 'Частично зарезервирован'), ('ready_to_ship', 'Готов к отправке'), ('shipped', 'Отправлен'), ('completed', 'Завершен'), ('cancelled', 'Отменен'), ('draft', 'Черновик (legacy)'), ('placed', 'Оформлен (legacy)')], default='new', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Промежуточная сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итоговая сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма позиции'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='operator_note',
            field=models.TextField(blank=True, verbose_name='Комментарий оператора'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='procurement_status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('awaiting_procurement', 'Ожидает закупки'), ('reserved', 'Зарезервирован'), ('partially_reserved', 'Частично зарезервирован'), ('unavailable', 'Недоступен'), ('cancelled', 'Отменен')], default='pending', max_length=32, verbose_name='Статус закупки'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_sku',
            field=models.CharField(max_length=64, verbose_name='SKU товара'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='recommended_supplier_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_for_order_items', to='pricing.supplieroffer', verbose_name='Рекомендованный оффер поставщика'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='selected_supplier_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_order_items', to='pricing.supplieroffer', verbose_name='Выбранный оффер поставщика'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='shortage_reason_code',
            field=models.CharField(blank=True, choices=[('stock_shortage', 'Недостаток остатка'), ('price_changed', 'Изменилась цена'), ('supplier_unavailable', 'Поставщик недоступен'), ('lead_time_too_long', 'Слишком долгий срок поставки'), ('other', 'Другое')], max_length=32, verbose_name='Причина дефицита'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='shortage_reason_note',
            field=models.TextField(blank=True, verbose_name='Комментарий по дефициту'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='snapshot_availability_label',
            field=models.CharField(default='', max_length=64, verbose_name='Подпись доступности в снимке'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='snapshot_availability_status',
            field=models.CharField(default='', max_length=32, verbose_name='Статус доступности в снимке'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='snapshot_currency',
            field=models.CharField(default='UAH', max_length=3, verbose_name='Валюта снимка'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='snapshot_estimated_delivery_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Срок доставки в снимке, дней'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='snapshot_offer_explainability',
            field=models.JSONField(blank=True, default=dict, verbose_name='Детали выбора оффера'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='snapshot_procurement_source',
            field=models.CharField(default='', max_length=255, verbose_name='Источник закупки в снимке'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='snapshot_selected_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_for_order_items', to='pricing.supplieroffer', verbose_name='Выбранный оффер в снимке'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='snapshot_sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена продажи в снимке'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена за единицу'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
