# Generated by Django 6.0.4 on 2026-04-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0004_novaposhtasenderprofile_ordernovaposhtawaybill_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordernovaposhtawaybill",
            name="recipient_contact_ref",
            field=models.CharField(blank=True, max_length=36, verbose_name="Ref контактного лица получателя"),
        ),
        migrations.AddField(
            model_name="ordernovaposhtawaybill",
            name="recipient_counterparty_ref",
            field=models.CharField(blank=True, max_length=36, verbose_name="Ref контрагента получателя"),
        ),
    ]
