# Generated by ChatGPT Codex on 2026-04-19

import uuid
from django.db import migrations, models


def forwards_create_order_payments(apps, schema_editor):
    Order = apps.get_model("commerce", "Order")
    OrderPayment = apps.get_model("commerce", "OrderPayment")

    Order.objects.filter(payment_method="card_placeholder").update(payment_method="monobank")

    for order in Order.objects.all().iterator():
        is_monobank = order.payment_method == "monobank"
        OrderPayment.objects.get_or_create(
            order_id=order.id,
            defaults={
                "provider": "monobank" if is_monobank else "cash_on_delivery",
                "method": "monobank" if is_monobank else "cash_on_delivery",
                "status": "pending",
                "amount": order.total,
                "currency": order.currency,
            },
        )


def backwards_restore_placeholder(apps, schema_editor):
    Order = apps.get_model("commerce", "Order")
    Order.objects.filter(payment_method="monobank").update(payment_method="card_placeholder")


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0005_ordernovaposhtawaybill_recipient_counterparty_and_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonobankSettings",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(default="default", max_length=32, unique=True, verbose_name="Код профиля")),
                ("is_enabled", models.BooleanField(default=False, verbose_name="Monobank включен")),
                ("merchant_token", models.CharField(blank=True, max_length=255, verbose_name="Merchant token")),
                ("widget_key_id", models.CharField(blank=True, max_length=255, verbose_name="Widget key id")),
                ("widget_private_key", models.TextField(blank=True, verbose_name="Widget private key (PEM)")),
                ("webhook_public_key", models.TextField(blank=True, verbose_name="Webhook public key (PEM)")),
                (
                    "last_connection_checked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Последняя проверка соединения"),
                ),
                ("last_connection_ok", models.BooleanField(blank=True, null=True, verbose_name="Последняя проверка успешна")),
                ("last_connection_message", models.TextField(blank=True, verbose_name="Сообщение последней проверки")),
                ("last_sync_at", models.DateTimeField(blank=True, null=True, verbose_name="Последняя синхронизация")),
                (
                    "last_currency_sync_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Последнее обновление курсов"),
                ),
                ("currency_rates_snapshot", models.JSONField(blank=True, default=list, verbose_name="Снимок курсов валют")),
            ],
            options={
                "verbose_name": "Настройки Monobank",
                "verbose_name_plural": "Настройки Monobank",
            },
        ),
        migrations.CreateModel(
            name="OrderPayment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("monobank", "Monobank"), ("cash_on_delivery", "Наложенный платеж")],
                        default="cash_on_delivery",
                        max_length=32,
                        verbose_name="Провайдер оплаты",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("monobank", "Monobank"), ("cash_on_delivery", "Наложенный платеж")],
                        default="cash_on_delivery",
                        max_length=32,
                        verbose_name="Метод оплаты",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает создания"),
                            ("created", "Создан"),
                            ("processing", "Обрабатывается"),
                            ("hold", "Холд"),
                            ("success", "Успешно"),
                            ("failure", "Ошибка"),
                            ("reversed", "Отменен"),
                            ("expired", "Истек"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="Статус оплаты",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Сумма")),
                ("currency", models.CharField(default="UAH", max_length=3, verbose_name="Валюта")),
                ("monobank_invoice_id", models.CharField(blank=True, max_length=128, verbose_name="Invoice ID Monobank")),
                ("monobank_reference", models.CharField(blank=True, max_length=128, verbose_name="Reference Monobank")),
                ("monobank_page_url", models.URLField(blank=True, max_length=1024, verbose_name="Page URL Monobank")),
                ("failure_reason", models.TextField(blank=True, verbose_name="Причина ошибки")),
                ("provider_created_at", models.DateTimeField(blank=True, null=True, verbose_name="Создан у провайдера")),
                ("provider_modified_at", models.DateTimeField(blank=True, null=True, verbose_name="Изменен у провайдера")),
                ("last_webhook_received_at", models.DateTimeField(blank=True, null=True, verbose_name="Последний webhook")),
                ("last_sync_at", models.DateTimeField(blank=True, null=True, verbose_name="Последняя синхронизация")),
                ("raw_create_payload", models.JSONField(blank=True, default=dict, verbose_name="Сырой payload создания")),
                ("raw_create_response", models.JSONField(blank=True, default=dict, verbose_name="Сырой ответ создания")),
                ("raw_status_payload", models.JSONField(blank=True, default=dict, verbose_name="Сырой payload статуса")),
                ("raw_last_webhook_payload", models.JSONField(blank=True, default=dict, verbose_name="Сырой payload webhook")),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=models.deletion.CASCADE,
                        related_name="payment",
                        to="commerce.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оплата заказа",
                "verbose_name_plural": "Оплаты заказов",
            },
        ),
        migrations.AddIndex(
            model_name="orderpayment",
            index=models.Index(fields=["provider", "status"], name="commerce_order_payment_provider_status_idx"),
        ),
        migrations.AddIndex(
            model_name="orderpayment",
            index=models.Index(fields=["monobank_invoice_id"], name="commerce_order_payment_invoice_idx"),
        ),
        migrations.AddIndex(
            model_name="orderpayment",
            index=models.Index(fields=["provider_modified_at"], name="commerce_order_payment_modified_idx"),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("monobank", "Monobank"),
                    ("cash_on_delivery", "Наложенный платеж"),
                    ("card_placeholder", "Оплата картой (legacy)"),
                ],
                max_length=32,
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.RunPython(forwards_create_order_payments, backwards_restore_placeholder),
    ]
