# Generated by Django 6.0.4 on 2026-04-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_monobank_settings_orderpayment_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderpayment',
            new_name='com_ordpay_prov_stat_idx',
            old_name='commerce_order_payment_provider_status_idx',
        ),
        migrations.RenameIndex(
            model_name='orderpayment',
            new_name='com_ordpay_invoice_idx',
            old_name='commerce_order_payment_invoice_idx',
        ),
        migrations.RenameIndex(
            model_name='orderpayment',
            new_name='com_ordpay_mod_at_idx',
            old_name='commerce_order_payment_modified_idx',
        ),
    ]
