# Generated by ChatGPT Codex on 2026-04-20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0008_order_delivery_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="NovaPaySettings",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(default="default", max_length=32, unique=True, verbose_name="Код профиля")),
                ("is_enabled", models.BooleanField(default=False, verbose_name="Nova Pay включен")),
                ("merchant_id", models.CharField(blank=True, max_length=64, verbose_name="Merchant ID")),
                ("api_token", models.CharField(blank=True, max_length=255, verbose_name="API token (X-Sign)")),
            ],
            options={
                "verbose_name": "Настройки Nova Pay",
                "verbose_name_plural": "Настройки Nova Pay",
            },
        ),
    ]
