# Generated by Django 6.0.4 on 2026-04-21 06:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_novapay_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiqPaySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default='default', max_length=32, unique=True, verbose_name='Код профиля')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='LiqPay включен')),
                ('public_key', models.CharField(blank=True, max_length=255, verbose_name='Public key')),
                ('private_key', models.CharField(blank=True, max_length=255, verbose_name='Private key')),
            ],
            options={
                'verbose_name': 'Настройки LiqPay',
                'verbose_name_plural': 'Настройки LiqPay',
            },
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='liqpay_order_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='Order ID LiqPay'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='liqpay_page_url',
            field=models.URLField(blank=True, max_length=1024, verbose_name='Page URL LiqPay'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='liqpay_payment_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='Payment ID LiqPay'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('monobank', 'Monobank'), ('liqpay', 'LiqPay'), ('cash_on_delivery', 'Наложенный платеж'), ('card_placeholder', 'Оплата картой (legacy)')], max_length=32, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='method',
            field=models.CharField(choices=[('monobank', 'Monobank'), ('liqpay', 'LiqPay'), ('cash_on_delivery', 'Наложенный платеж')], default='cash_on_delivery', max_length=32, verbose_name='Метод оплаты'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='provider',
            field=models.CharField(choices=[('monobank', 'Monobank'), ('liqpay', 'LiqPay'), ('cash_on_delivery', 'Наложенный платеж')], default='cash_on_delivery', max_length=32, verbose_name='Провайдер оплаты'),
        ),
    ]
