# Generated by Django 6.0.4 on 2026-04-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_liqpaysettings_orderpayment_liqpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liqpaysettings',
            name='last_connection_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка соединения'),
        ),
        migrations.AddField(
            model_name='liqpaysettings',
            name='last_connection_message',
            field=models.TextField(blank=True, verbose_name='Сообщение последней проверки'),
        ),
        migrations.AddField(
            model_name='liqpaysettings',
            name='last_connection_ok',
            field=models.BooleanField(blank=True, null=True, verbose_name='Последняя проверка успешна'),
        ),
        migrations.AddField(
            model_name='novapaysettings',
            name='last_connection_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка соединения'),
        ),
        migrations.AddField(
            model_name='novapaysettings',
            name='last_connection_message',
            field=models.TextField(blank=True, verbose_name='Сообщение последней проверки'),
        ),
        migrations.AddField(
            model_name='novapaysettings',
            name='last_connection_ok',
            field=models.BooleanField(blank=True, null=True, verbose_name='Последняя проверка успешна'),
        ),
    ]
