# Generated by Django 6.0.4 on 2026-04-21 11:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0011_liqpaysettings_last_connection_checked_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='applied_promo_code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Примененный промокод'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_breakdown',
            field=models.JSONField(blank=True, default=dict, verbose_name='Детали скидки'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма скидки'),
        ),
        migrations.CreateModel(
            name='LoyaltyPromoCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Промокод')),
                ('reason', models.CharField(max_length=255, verbose_name='Причина выдачи')),
                ('discount_type', models.CharField(choices=[('delivery_fee', 'Скидка на доставку'), ('product_markup', 'Скидка на товарную наценку')], max_length=32, verbose_name='Тип скидки')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент скидки')),
                ('usage_limit', models.PositiveIntegerField(default=1, verbose_name='Лимит использований')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Использований')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('disabled', 'Отключен')], default='active', max_length=16, verbose_name='Статус')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Срок действия')),
                ('last_redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее применение')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_promo_codes', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_loyalty_promo_codes', to=settings.AUTH_USER_MODEL, verbose_name='Кто выдал')),
                ('last_redeemed_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_loyalty_promo_codes', to='commerce.order', verbose_name='Заказ последнего применения')),
            ],
            options={
                'verbose_name': 'Лояльность: промокод',
                'verbose_name_plural': 'Лояльность: промокоды',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LoyaltyPromoEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('issued', 'Выдача'), ('redeemed', 'Применение'), ('disabled', 'Отключение')], max_length=32, verbose_name='Событие')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные события')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_promo_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='commerce.loyaltypromocode', verbose_name='Промокод')),
            ],
            options={
                'verbose_name': 'Лояльность: событие промокода',
                'verbose_name_plural': 'Лояльность: события промокода',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LoyaltyPromoRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Запрошенный процент')),
                ('applied_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Фактический процент')),
                ('delivery_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Скидка на доставку')),
                ('product_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Скидка на товар')),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая скидка')),
                ('currency', models.CharField(default='UAH', max_length=3, verbose_name='Валюта')),
                ('discount_payload', models.JSONField(blank=True, default=dict, verbose_name='Детали скидки')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_promo_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_redemptions', to='commerce.order', verbose_name='Заказ')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='commerce.loyaltypromocode', verbose_name='Промокод')),
            ],
            options={
                'verbose_name': 'Лояльность: применение промокода',
                'verbose_name_plural': 'Лояльность: применения промокодов',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='loyaltypromocode',
            index=models.Index(fields=['code'], name='commerce_loyalty_code_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltypromocode',
            index=models.Index(fields=['customer', 'status'], name='com_loyl_customer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltypromocode',
            index=models.Index(fields=['expires_at'], name='commerce_loyalty_expires_idx'),
        ),
        migrations.AddConstraint(
            model_name='loyaltypromoredemption',
            constraint=models.UniqueConstraint(fields=('promo_code', 'order'), name='commerce_loyalty_redemption_order_unique'),
        ),
    ]
