# Generated by Django 6.0.4 on 2026-04-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0014_vchasno_kasa_settings_and_order_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vchasnokasasettings',
            name='api_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='API токен заказов Вчасно'),
        ),
    ]
