# Generated by Django 6.0.4 on 2026-04-24

from django.db import migrations, models


def populate_selected_vchasno_codes(apps, schema_editor):
    VchasnoKasaSettings = apps.get_model("commerce", "VchasnoKasaSettings")
    for settings in VchasnoKasaSettings.objects.all():
        updated_fields: list[str] = []

        payment_methods = settings.selected_payment_methods if isinstance(settings.selected_payment_methods, list) else []
        if not payment_methods:
            default_payment_type = getattr(settings, "default_payment_type", None)
            if default_payment_type is not None:
                payment_methods = [str(default_payment_type).strip()]
                updated_fields.append("selected_payment_methods")

        tax_groups = settings.selected_tax_groups if isinstance(settings.selected_tax_groups, list) else []
        if not tax_groups:
            default_tax_group = str(getattr(settings, "default_tax_group", "") or "").strip()
            if default_tax_group:
                tax_groups = [default_tax_group]
                updated_fields.append("selected_tax_groups")

        if updated_fields:
            settings.selected_payment_methods = payment_methods
            settings.selected_tax_groups = tax_groups
            settings.save(update_fields=updated_fields)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0015_alter_vchasnokasasettings_api_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="vchasnokasasettings",
            name="selected_payment_methods",
            field=models.JSONField(blank=True, default=list, verbose_name="Обрані засоби оплат каси"),
        ),
        migrations.AddField(
            model_name="vchasnokasasettings",
            name="selected_tax_groups",
            field=models.JSONField(blank=True, default=list, verbose_name="Обрані податкові групи каси"),
        ),
        migrations.RunPython(populate_selected_vchasno_codes, noop_reverse),
    ]
