# Generated by Django 6.0.4 on 2026-04-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0016_vchasno_kasa_selected_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="vchasnokasasettings",
            name="fiscal_api_token",
            field=models.CharField(blank=True, max_length=255, verbose_name="API токен каси Вчасно"),
        ),
    ]
