# Generated by Django 6.0.4 on 2026-05-19 09:38

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_product_name_index'),
        ('commerce', '0021_orderevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата получения заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='received_at_source',
            field=models.CharField(blank=True, choices=[('nova_poshta_tracking', 'Отслеживание Новой Почты'), ('order_completed_fallback', 'Переход в завершен (fallback)')], default='', max_length=64, verbose_name='Источник даты получения'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_eligible_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Доступен возврат до'),
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Номер возврата')),
                ('status', models.CharField(choices=[('new', 'Новая заявка'), ('approved', 'Одобрено'), ('rejected', 'Отказано'), ('awaiting_ttn', 'Ожидаем ТТН'), ('in_transit', 'В пути'), ('received', 'Получено'), ('accepted', 'Принято'), ('refund_processing', 'Возврат средств в обработке'), ('refunded', 'Средства возвращены'), ('cancelled', 'Отменено')], db_index=True, default='new', max_length=32, verbose_name='Статус')),
                ('reason_comment', models.TextField(verbose_name='Причина возврата')),
                ('admin_comment', models.TextField(blank=True, default='', verbose_name='Комментарий администратора')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Причина отказа')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сумма возврата')),
                ('refund_status', models.CharField(choices=[('none', 'Не начат'), ('processing', 'В обработке'), ('done', 'Выполнен'), ('failed', 'Ошибка')], default='none', max_length=32, verbose_name='Статус возврата средств')),
                ('refund_method', models.CharField(blank=True, default='', max_length=64, verbose_name='Способ возврата')),
                ('customer_return_tracking_number', models.CharField(blank=True, default='', max_length=32, verbose_name='ТТН клиента')),
                ('customer_return_tracking_submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='ТТН отправлена')),
                ('nova_poshta_return_status_code', models.CharField(blank=True, default='', max_length=32, verbose_name='Код статуса НП')),
                ('nova_poshta_return_status_text', models.CharField(blank=True, default='', max_length=255, verbose_name='Текст статуса НП')),
                ('nova_poshta_return_status_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Статус НП синхронизирован')),
                ('return_address_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Снимок адреса возврата')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Получено магазином')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Одобрено')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Отклонено')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Принято')),
                ('refund_processing_at', models.DateTimeField(blank=True, null=True, verbose_name='Возврат в обработке')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='Средства возвращены')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='commerce.order', verbose_name='Заказ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на возврат',
                'verbose_name_plural': 'Заявки на возврат',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReturnEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, default='', max_length=32, verbose_name='Из статуса')),
                ('to_status', models.CharField(blank=True, default='', max_length=32, verbose_name='В статус')),
                ('comment', models.CharField(blank=True, default='', max_length=500, verbose_name='Комментарий')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_events', to=settings.AUTH_USER_MODEL, verbose_name='Кто выполнил')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='commerce.returnrequest', verbose_name='Заявка на возврат')),
            ],
            options={
                'verbose_name': 'Событие возврата',
                'verbose_name_plural': 'События возврата',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReturnRequestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name_snapshot', models.CharField(max_length=255, verbose_name='Название товара')),
                ('product_sku_snapshot', models.CharField(max_length=64, verbose_name='SKU товара')),
                ('quantity_ordered', models.PositiveIntegerField(default=1, verbose_name='Количество в заказе')),
                ('quantity_requested', models.PositiveIntegerField(default=1, verbose_name='Запрошено к возврату')),
                ('quantity_approved', models.PositiveIntegerField(default=0, verbose_name='Одобрено к возврату')),
                ('original_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Цена на момент заказа')),
                ('original_line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сумма позиции на момент заказа')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сумма возврата')),
                ('is_returnable_snapshot', models.BooleanField(default=True, verbose_name='Возвратный товар')),
                ('non_returnable_reason_snapshot', models.CharField(blank=True, default='', max_length=255, verbose_name='Причина невозвратности')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='commerce.orderitem', verbose_name='Позиция заказа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='catalog.product', verbose_name='Товар')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.returnrequest', verbose_name='Заявка на возврат')),
            ],
            options={
                'verbose_name': 'Позиция заявки на возврат',
                'verbose_name_plural': 'Позиции заявок на возврат',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['user', '-created_at'], name='com_ret_usr_created_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['order', '-created_at'], name='com_ret_ord_created_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['status', '-created_at'], name='com_ret_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='returnevent',
            index=models.Index(fields=['return_request', '-created_at'], name='com_ret_evt_req_created_idx'),
        ),
    ]
