# Generated by Django 6.0.4 on 2026-05-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0022_order_received_at_order_received_at_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequestNumberSequence',
            fields=[
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='Последний номер возврата')),
            ],
            options={
                'verbose_name': 'Счетчик номеров возвратов',
                'verbose_name_plural': 'Счетчики номеров возвратов',
            },
        ),
    ]
