# Generated by Django 6.0.4 on 2026-04-11 13:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=140)),
                ('year_start', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year_end', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('model__make__name', 'model__name', '-year_start'),
            },
        ),
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
            options={
                'verbose_name': 'Vehicle make',
                'verbose_name_plural': 'Vehicle makes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VehicleEngine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=140)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('displacement_cc', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('ev', 'EV'), ('other', 'Other')], default='other', max_length=16)),
                ('power_hp', models.PositiveIntegerField(blank=True, null=True)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engines', to='vehicles.vehiclegeneration')),
            ],
            options={
                'ordering': ('generation__model__make__name', 'generation__model__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='vehicles.vehiclemake')),
            ],
            options={
                'ordering': ('make__name', 'name'),
            },
        ),
        migrations.AddField(
            model_name='vehiclegeneration',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='vehicles.vehiclemodel'),
        ),
        migrations.CreateModel(
            name='VehicleModification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('body_type', models.CharField(blank=True, max_length=80)),
                ('transmission', models.CharField(blank=True, max_length=80)),
                ('drivetrain', models.CharField(blank=True, max_length=80)),
                ('year_start', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year_end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='vehicles.vehicleengine')),
            ],
            options={
                'ordering': ('engine__generation__model__make__name', 'engine__generation__model__name', 'name'),
            },
        ),
        migrations.AddConstraint(
            model_name='vehicleengine',
            constraint=models.UniqueConstraint(fields=('generation', 'name', 'code'), name='vehicles_engine_unique_generation_name_code'),
        ),
        migrations.AddConstraint(
            model_name='vehiclemodel',
            constraint=models.UniqueConstraint(fields=('make', 'slug'), name='vehicles_model_unique_slug_per_make'),
        ),
        migrations.AddConstraint(
            model_name='vehiclegeneration',
            constraint=models.UniqueConstraint(fields=('model', 'name', 'year_start'), name='vehicles_generation_unique_model_name_start'),
        ),
        migrations.AddConstraint(
            model_name='vehiclemodification',
            constraint=models.UniqueConstraint(fields=('engine', 'name', 'year_start'), name='vehicles_modification_unique_engine_name_start'),
        ),
    ]
