# Generated by Django 6.0.4 on 2026-04-12 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleengine',
            options={'ordering': ('generation__model__make__name', 'generation__model__name', 'name'), 'verbose_name': 'Двигатель', 'verbose_name_plural': 'Двигатели'},
        ),
        migrations.AlterModelOptions(
            name='vehiclegeneration',
            options={'ordering': ('model__make__name', 'model__name', '-year_start'), 'verbose_name': 'Поколение автомобиля', 'verbose_name_plural': 'Поколения автомобилей'},
        ),
        migrations.AlterModelOptions(
            name='vehiclemake',
            options={'ordering': ('name',), 'verbose_name': 'Марка автомобиля', 'verbose_name_plural': 'Марки автомобилей'},
        ),
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'ordering': ('make__name', 'name'), 'verbose_name': 'Модель автомобиля', 'verbose_name_plural': 'Модели автомобилей'},
        ),
        migrations.AlterModelOptions(
            name='vehiclemodification',
            options={'ordering': ('engine__generation__model__make__name', 'engine__generation__model__name', 'name'), 'verbose_name': 'Модификация автомобиля', 'verbose_name_plural': 'Модификации автомобилей'},
        ),
        migrations.AlterField(
            model_name='vehicleengine',
            name='code',
            field=models.CharField(blank=True, max_length=64, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='vehicleengine',
            name='displacement_cc',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Объем, см3'),
        ),
        migrations.AlterField(
            model_name='vehicleengine',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('hybrid', 'Гибрид'), ('ev', 'Электро'), ('other', 'Другое')], default='other', max_length=16, verbose_name='Тип топлива'),
        ),
        migrations.AlterField(
            model_name='vehicleengine',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engines', to='vehicles.vehiclegeneration', verbose_name='Поколение'),
        ),
        migrations.AlterField(
            model_name='vehicleengine',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vehicleengine',
            name='power_hp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Мощность, л.с.'),
        ),
        migrations.AlterField(
            model_name='vehiclegeneration',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='vehicles.vehiclemodel', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='vehiclegeneration',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vehiclegeneration',
            name='year_end',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год окончания'),
        ),
        migrations.AlterField(
            model_name='vehiclegeneration',
            name='year_start',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год начала'),
        ),
        migrations.AlterField(
            model_name='vehiclemake',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vehiclemake',
            name='slug',
            field=models.SlugField(max_length=140, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='vehicles.vehiclemake', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='slug',
            field=models.SlugField(max_length=140, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='vehiclemodification',
            name='body_type',
            field=models.CharField(blank=True, max_length=80, verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='vehiclemodification',
            name='drivetrain',
            field=models.CharField(blank=True, max_length=80, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='vehiclemodification',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='vehicles.vehicleengine', verbose_name='Двигатель'),
        ),
        migrations.AlterField(
            model_name='vehiclemodification',
            name='name',
            field=models.CharField(max_length=160, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vehiclemodification',
            name='transmission',
            field=models.CharField(blank=True, max_length=80, verbose_name='Трансмиссия'),
        ),
        migrations.AlterField(
            model_name='vehiclemodification',
            name='year_end',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год окончания'),
        ),
        migrations.AlterField(
            model_name='vehiclemodification',
            name='year_start',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год начала'),
        ),
    ]
