# Generated by Django 6.0.4 on 2026-04-11 19:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('pricing', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('trigger', models.CharField(default='manual', max_length=64)),
                ('dry_run', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('parsed_rows', models.PositiveIntegerField(default=0)),
                ('offers_created', models.PositiveIntegerField(default=0)),
                ('offers_updated', models.PositiveIntegerField(default=0)),
                ('offers_skipped', models.PositiveIntegerField(default=0)),
                ('errors_count', models.PositiveIntegerField(default=0)),
                ('repriced_products', models.PositiveIntegerField(default=0)),
                ('reindexed_products', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ImportArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=1024)),
                ('file_format', models.CharField(blank=True, max_length=32)),
                ('file_size', models.BigIntegerField(default=0)),
                ('checksum_sha1', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('parsed_rows', models.PositiveIntegerField(default=0)),
                ('errors_count', models.PositiveIntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='supplier_imports.importrun')),
            ],
            options={
                'ordering': ('file_name',),
            },
        ),
        migrations.CreateModel(
            name='ImportSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('parser_type', models.CharField(choices=[('utr', 'UTR'), ('gpl', 'GPL')], max_length=16)),
                ('input_path', models.CharField(blank=True, max_length=512)),
                ('file_patterns', models.JSONField(blank=True, default=list)),
                ('mapping_config', models.JSONField(blank=True, default=dict)),
                ('parser_options', models.JSONField(blank=True, default=dict)),
                ('default_currency', models.CharField(default='UAH', max_length=3)),
                ('auto_reprice', models.BooleanField(default=True)),
                ('auto_reindex', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_sources', to='pricing.supplier')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='importrun',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='supplier_imports.importsource'),
        ),
        migrations.CreateModel(
            name='ImportRowError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('external_sku', models.CharField(blank=True, max_length=128)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('message', models.TextField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='row_errors', to='supplier_imports.importartifact')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_errors', to='supplier_imports.importrun')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_errors', to='supplier_imports.importsource')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='importartifact',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='supplier_imports.importsource'),
        ),
        migrations.CreateModel(
            name='SupplierRawOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('external_sku', models.CharField(max_length=128)),
                ('article', models.CharField(blank=True, max_length=128)),
                ('normalized_article', models.CharField(db_index=True, max_length=128)),
                ('brand_name', models.CharField(blank=True, max_length=180)),
                ('normalized_brand', models.CharField(blank=True, db_index=True, max_length=180)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock_qty', models.IntegerField(default=0)),
                ('lead_time_days', models.PositiveSmallIntegerField(default=0)),
                ('is_valid', models.BooleanField(default=True)),
                ('skip_reason', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_offers', to='supplier_imports.importartifact')),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_supplier_offers', to='catalog.product')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_offers', to='supplier_imports.importrun')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_offers', to='supplier_imports.importsource')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_offers', to='pricing.supplier')),
            ],
            options={
                'ordering': ('source__code', 'external_sku'),
            },
        ),
    ]
