# Generated by Django 6.0.4 on 2026-04-12 06:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('supplier_imports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierrawoffer',
            name='ignored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierrawoffer',
            name='last_matched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierrawoffer',
            name='match_candidate_product_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='supplierrawoffer',
            name='match_reason',
            field=models.CharField(blank=True, choices=[('brand_conflict', 'Brand conflict'), ('article_conflict', 'Article conflict'), ('ambiguous_match', 'Ambiguous match'), ('missing_brand', 'Missing brand'), ('missing_article', 'Missing article')], db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='supplierrawoffer',
            name='match_status',
            field=models.CharField(choices=[('unmatched', 'Unmatched'), ('auto_matched', 'Auto matched'), ('manual_match_required', 'Manual match required'), ('manually_matched', 'Manually matched'), ('ignored', 'Ignored')], db_index=True, default='unmatched', max_length=32),
        ),
        migrations.AddField(
            model_name='supplierrawoffer',
            name='matched_manually_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierrawoffer',
            name='matched_manually_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manually_matched_raw_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierrawoffer',
            name='matching_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OfferMatchReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('auto_attempt', 'Auto attempt'), ('retry_matching', 'Retry matching'), ('manual_confirm', 'Manual confirm'), ('ignore', 'Ignore'), ('bulk_auto_match', 'Bulk auto match'), ('bulk_ignore', 'Bulk ignore')], max_length=32)),
                ('status_before', models.CharField(blank=True, max_length=32)),
                ('status_after', models.CharField(blank=True, max_length=32)),
                ('reason', models.CharField(blank=True, max_length=64)),
                ('candidate_product_ids', models.JSONField(blank=True, default=list)),
                ('note', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_match_reviews', to=settings.AUTH_USER_MODEL)),
                ('raw_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_reviews', to='supplier_imports.supplierrawoffer')),
                ('selected_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_match_reviews', to='catalog.product')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
