# Generated by Django 6.0.4 on 2026-04-12 07:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('pricing', '0002_initial'),
        ('supplier_imports', '0002_supplierrawoffer_ignored_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsource',
            name='auto_reindex_after_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importsource',
            name='auto_reprice_after_import',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='importsource',
            name='is_auto_import_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importsource',
            name='last_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importsource',
            name='last_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importsource',
            name='last_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importsource',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importsource',
            name='schedule_cron',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='importsource',
            name='schedule_timezone',
            field=models.CharField(default='Europe/Kyiv', max_length=64),
        ),
        migrations.AddField(
            model_name='supplierrawoffer',
            name='article_normalization_trace',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='supplierrawoffer',
            name='brand_normalization_trace',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ArticleNormalizationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('rule_type', models.CharField(choices=[('remove_separators', 'Remove separators'), ('strip_prefix', 'Strip prefix'), ('strip_suffix', 'Strip suffix'), ('regex_replace', 'Regex replace'), ('force_uppercase', 'Force uppercase')], max_length=32)),
                ('pattern', models.CharField(blank=True, max_length=180)),
                ('replacement', models.CharField(blank=True, max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100)),
                ('notes', models.TextField(blank=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_rules', to='supplier_imports.importsource')),
            ],
            options={
                'ordering': ('-priority', 'name'),
                'indexes': [models.Index(fields=['source', 'is_active', 'priority'], name='supplier_im_source__1b2d80_idx'), models.Index(fields=['rule_type', 'is_active'], name='supplier_im_rule_ty_1f9e16_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportRunQuality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('matched_rows', models.PositiveIntegerField(default=0)),
                ('auto_matched_rows', models.PositiveIntegerField(default=0)),
                ('manual_matched_rows', models.PositiveIntegerField(default=0)),
                ('ignored_rows', models.PositiveIntegerField(default=0)),
                ('unmatched_rows', models.PositiveIntegerField(default=0)),
                ('conflict_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('match_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('error_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('match_rate_delta', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('error_rate_delta', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('requires_operator_attention', models.BooleanField(default=False)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('previous_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_comparisons', to='supplier_imports.importrun')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality', to='supplier_imports.importrun')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_runs', to='supplier_imports.importsource')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['source', '-created_at'], name='supplier_im_source__c3df37_idx'), models.Index(fields=['requires_operator_attention', '-created_at'], name='supplier_im_require_4f5b28_idx'), models.Index(fields=['status', '-created_at'], name='supplier_im_status_92d45c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupplierBrandAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_brand_name', models.CharField(blank=True, max_length=180)),
                ('supplier_brand_alias', models.CharField(max_length=180)),
                ('normalized_alias', models.CharField(db_index=True, max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100)),
                ('notes', models.TextField(blank=True)),
                ('canonical_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_brand_aliases', to='catalog.brand')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_aliases', to='supplier_imports.importsource')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_aliases', to='pricing.supplier')),
            ],
            options={
                'ordering': ('supplier__code', 'source__code', '-priority', 'normalized_alias'),
                'indexes': [models.Index(fields=['normalized_alias', 'is_active', 'priority'], name='supplier_im_normali_94139e_idx'), models.Index(fields=['source', 'is_active', 'priority'], name='supplier_im_source__463c4a_idx'), models.Index(fields=['supplier', 'is_active', 'priority'], name='supplier_im_supplie_9d1fc9_idx')],
            },
        ),
    ]
