# Generated by Django 6.0.4 on 2026-04-12 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_attribute_options_alter_attributevalue_options_and_more'),
        ('pricing', '0004_alter_currencyrate_options_and_more'),
        ('supplier_imports', '0003_importsource_auto_reindex_after_import_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlenormalizationrule',
            options={'ordering': ('-priority', 'name'), 'verbose_name': 'Правило нормализации артикула', 'verbose_name_plural': 'Правила нормализации артикулов'},
        ),
        migrations.AlterModelOptions(
            name='importartifact',
            options={'ordering': ('file_name',), 'verbose_name': 'Артефакт импорта', 'verbose_name_plural': 'Артефакты импорта'},
        ),
        migrations.AlterModelOptions(
            name='importrowerror',
            options={'ordering': ('-created_at',), 'verbose_name': 'Ошибка строки импорта', 'verbose_name_plural': 'Ошибки строк импорта'},
        ),
        migrations.AlterModelOptions(
            name='importrun',
            options={'ordering': ('-created_at',), 'verbose_name': 'Запуск импорта', 'verbose_name_plural': 'Запуски импорта'},
        ),
        migrations.AlterModelOptions(
            name='importrunquality',
            options={'ordering': ('-created_at',), 'verbose_name': 'Качество запуска импорта', 'verbose_name_plural': 'Качество запусков импорта'},
        ),
        migrations.AlterModelOptions(
            name='importsource',
            options={'ordering': ('name',), 'verbose_name': 'Источник импорта', 'verbose_name_plural': 'Источники импорта'},
        ),
        migrations.AlterModelOptions(
            name='offermatchreview',
            options={'ordering': ('-created_at',), 'verbose_name': 'Проверка сопоставления оффера', 'verbose_name_plural': 'Проверки сопоставления офферов'},
        ),
        migrations.AlterModelOptions(
            name='supplierbrandalias',
            options={'ordering': ('supplier__code', 'source__code', '-priority', 'normalized_alias'), 'verbose_name': 'Алиас бренда поставщика', 'verbose_name_plural': 'Алиасы брендов поставщиков'},
        ),
        migrations.AlterModelOptions(
            name='supplierrawoffer',
            options={'ordering': ('source__code', 'external_sku'), 'verbose_name': 'Сырой оффер поставщика', 'verbose_name_plural': 'Сырые офферы поставщиков'},
        ),
        migrations.AlterField(
            model_name='articlenormalizationrule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='articlenormalizationrule',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='articlenormalizationrule',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='articlenormalizationrule',
            name='pattern',
            field=models.CharField(blank=True, max_length=180, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='articlenormalizationrule',
            name='priority',
            field=models.IntegerField(default=100, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='articlenormalizationrule',
            name='replacement',
            field=models.CharField(blank=True, max_length=180, verbose_name='Замена'),
        ),
        migrations.AlterField(
            model_name='articlenormalizationrule',
            name='rule_type',
            field=models.CharField(choices=[('remove_separators', 'Удалить разделители'), ('strip_prefix', 'Удалить префикс'), ('strip_suffix', 'Удалить суффикс'), ('regex_replace', 'Замена по регулярному выражению'), ('force_uppercase', 'Привести к верхнему регистру')], max_length=32, verbose_name='Тип правила'),
        ),
        migrations.AlterField(
            model_name='articlenormalizationrule',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_rules', to='supplier_imports.importsource', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='importartifact',
            name='checksum_sha1',
            field=models.CharField(blank=True, max_length=40, verbose_name='SHA1'),
        ),
        migrations.AlterField(
            model_name='importartifact',
            name='errors_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Ошибок'),
        ),
        migrations.AlterField(
            model_name='importartifact',
            name='file_format',
            field=models.CharField(blank=True, max_length=32, verbose_name='Формат файла'),
        ),
        migrations.AlterField(
            model_name='importartifact',
            name='file_name',
            field=models.CharField(max_length=255, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='importartifact',
            name='file_path',
            field=models.CharField(max_length=1024, verbose_name='Путь к файлу'),
        ),
        migrations.AlterField(
            model_name='importartifact',
            name='file_size',
            field=models.BigIntegerField(default=0, verbose_name='Размер файла'),
        ),
        migrations.AlterField(
            model_name='importartifact',
            name='parsed_rows',
            field=models.PositiveIntegerField(default=0, verbose_name='Разобрано строк'),
        ),
        migrations.AlterField(
            model_name='importartifact',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='supplier_imports.importrun', verbose_name='Запуск'),
        ),
        migrations.AlterField(
            model_name='importartifact',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='supplier_imports.importsource', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='importartifact',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('processed', 'Обработан'), ('skipped', 'Пропущен'), ('failed', 'Ошибка')], default='pending', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='importrowerror',
            name='artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='row_errors', to='supplier_imports.importartifact', verbose_name='Артефакт'),
        ),
        migrations.AlterField(
            model_name='importrowerror',
            name='error_code',
            field=models.CharField(blank=True, max_length=64, verbose_name='Код ошибки'),
        ),
        migrations.AlterField(
            model_name='importrowerror',
            name='external_sku',
            field=models.CharField(blank=True, max_length=128, verbose_name='Внешний SKU'),
        ),
        migrations.AlterField(
            model_name='importrowerror',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='importrowerror',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Полезная нагрузка'),
        ),
        migrations.AlterField(
            model_name='importrowerror',
            name='row_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер строки'),
        ),
        migrations.AlterField(
            model_name='importrowerror',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_errors', to='supplier_imports.importrun', verbose_name='Запуск'),
        ),
        migrations.AlterField(
            model_name='importrowerror',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_errors', to='supplier_imports.importsource', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='importrun',
            name='dry_run',
            field=models.BooleanField(default=False, verbose_name='Тестовый запуск'),
        ),
        migrations.AlterField(
            model_name='importrun',
            name='errors_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Ошибок'),
        ),
        migrations.AlterField(
            model_name='importrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершен'),
        ),
        migrations.AlterField(
            model_name='importrun',
            name='note',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='importrun',
            name='offers_created',
            field=models.PositiveIntegerField(default=0, verbose_name='Офферов создано'),
        ),
        migrations.AlterField(
            model_name='importrun',
            name='offers_skipped',
            field=models.PositiveIntegerField(default=0, verbose_name='Офферов пропущено'),
        ),
        migrations.AlterField(
            model_name='importrun',
            name='offers_updated',
            field=models.PositiveIntegerField(default=0, verbose_name='Офферов обновлено'),
        ),
        migrations.AlterField(
            model_name='importrun',
            name='parsed_rows',
            field=models.PositiveIntegerField(default=0, verbose_name='Разобрано строк'),
        ),
        migrations.AlterField(
            model_name='importrun',
            name='processed_rows',
            field=models.PositiveIntegerField(default=0, verbose_name='Обработано строк'),
        ),
        migrations.AlterField(
            model_name='importrun',
            name='reindexed_products',
            field=models.PositiveIntegerField(default=0, verbose_name='Переиндексировано товаров'),
        ),
        migrations.AlterField(
            model_name='importrun',
            name='repriced_products',
            field=models.PositiveIntegerField(default=0, verbose_name='Переоценено товаров'),
        ),
        migrations.AlterField(
            model_name='importrun',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='supplier_imports.importsource', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='importrun',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начат'),
        ),
        migrations.AlterField(
            model_name='importrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('success', 'Успешно'), ('partial', 'Частично'), ('failed', 'Ошибка')], default='pending', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='importrun',
            name='summary',
            field=models.JSONField(blank=True, default=dict, verbose_name='Сводка'),
        ),
        migrations.AlterField(
            model_name='importrun',
            name='trigger',
            field=models.CharField(default='manual', max_length=64, verbose_name='Триггер'),
        ),
        migrations.AlterField(
            model_name='importrunquality',
            name='previous_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_comparisons', to='supplier_imports.importrun', verbose_name='Предыдущий запуск'),
        ),
        migrations.AlterField(
            model_name='importrunquality',
            name='requires_operator_attention',
            field=models.BooleanField(default=False, verbose_name='Требует внимания оператора'),
        ),
        migrations.AlterField(
            model_name='importrunquality',
            name='run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality', to='supplier_imports.importrun', verbose_name='Запуск'),
        ),
        migrations.AlterField(
            model_name='importrunquality',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_runs', to='supplier_imports.importsource', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='importrunquality',
            name='status',
            field=models.CharField(default='pending', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='importsource',
            name='auto_reindex',
            field=models.BooleanField(default=False, verbose_name='Автоиндексация'),
        ),
        migrations.AlterField(
            model_name='importsource',
            name='auto_reindex_after_import',
            field=models.BooleanField(default=False, verbose_name='Автоиндексация после импорта'),
        ),
        migrations.AlterField(
            model_name='importsource',
            name='auto_reprice',
            field=models.BooleanField(default=True, verbose_name='Автопереоценка'),
        ),
        migrations.AlterField(
            model_name='importsource',
            name='auto_reprice_after_import',
            field=models.BooleanField(default=True, verbose_name='Автопереоценка после импорта'),
        ),
        migrations.AlterField(
            model_name='importsource',
            name='code',
            field=models.SlugField(max_length=64, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='importsource',
            name='default_currency',
            field=models.CharField(default='UAH', max_length=3, verbose_name='Валюта по умолчанию'),
        ),
        migrations.AlterField(
            model_name='importsource',
            name='file_patterns',
            field=models.JSONField(blank=True, default=list, verbose_name='Маски файлов'),
        ),
        migrations.AlterField(
            model_name='importsource',
            name='input_path',
            field=models.CharField(blank=True, max_length=512, verbose_name='Путь к входному файлу'),
        ),
        migrations.AlterField(
            model_name='importsource',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='importsource',
            name='is_auto_import_enabled',
            field=models.BooleanField(default=False, verbose_name='Автоимпорт включен'),
        ),
        migrations.AlterField(
            model_name='importsource',
            name='last_failed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск с ошибкой'),
        ),
        migrations.AlterField(
            model_name='importsource',
            name='last_finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее завершение'),
        ),
        migrations.AlterField(
            model_name='importsource',
            name='last_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний старт'),
        ),
        migrations.AlterField(
            model_name='importsource',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний успешный запуск'),
        ),
        migrations.AlterField(
            model_name='importsource',
            name='mapping_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Конфигурация маппинга'),
        ),
        migrations.AlterField(
            model_name='importsource',
            name='name',
            field=models.CharField(max_length=180, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='importsource',
            name='parser_options',
            field=models.JSONField(blank=True, default=dict, verbose_name='Опции парсера'),
        ),
        migrations.AlterField(
            model_name='importsource',
            name='parser_type',
            field=models.CharField(choices=[('utr', 'UTR'), ('gpl', 'GPL')], max_length=16, verbose_name='Тип парсера'),
        ),
        migrations.AlterField(
            model_name='importsource',
            name='schedule_cron',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Cron-расписание'),
        ),
        migrations.AlterField(
            model_name='importsource',
            name='schedule_timezone',
            field=models.CharField(default='Europe/Kyiv', max_length=64, verbose_name='Часовой пояс расписания'),
        ),
        migrations.AlterField(
            model_name='importsource',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_sources', to='pricing.supplier', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='offermatchreview',
            name='action',
            field=models.CharField(choices=[('auto_attempt', 'Автоматическая попытка'), ('retry_matching', 'Повторный матчинг'), ('manual_confirm', 'Ручное подтверждение'), ('ignore', 'Игнорировать'), ('bulk_auto_match', 'Массовый автомэтчинг'), ('bulk_ignore', 'Массовое игнорирование')], max_length=32, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='offermatchreview',
            name='candidate_product_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Кандидаты товаров'),
        ),
        migrations.AlterField(
            model_name='offermatchreview',
            name='note',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='offermatchreview',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_match_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='offermatchreview',
            name='raw_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_reviews', to='supplier_imports.supplierrawoffer', verbose_name='Сырой оффер'),
        ),
        migrations.AlterField(
            model_name='offermatchreview',
            name='reason',
            field=models.CharField(blank=True, max_length=64, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='offermatchreview',
            name='selected_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_match_reviews', to='catalog.product', verbose_name='Выбранный товар'),
        ),
        migrations.AlterField(
            model_name='offermatchreview',
            name='status_after',
            field=models.CharField(blank=True, max_length=32, verbose_name='Статус после'),
        ),
        migrations.AlterField(
            model_name='offermatchreview',
            name='status_before',
            field=models.CharField(blank=True, max_length=32, verbose_name='Статус до'),
        ),
        migrations.AlterField(
            model_name='supplierbrandalias',
            name='canonical_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_brand_aliases', to='catalog.brand', verbose_name='Канонический бренд'),
        ),
        migrations.AlterField(
            model_name='supplierbrandalias',
            name='canonical_brand_name',
            field=models.CharField(blank=True, max_length=180, verbose_name='Название канонического бренда'),
        ),
        migrations.AlterField(
            model_name='supplierbrandalias',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='supplierbrandalias',
            name='normalized_alias',
            field=models.CharField(db_index=True, max_length=180, verbose_name='Нормализованный алиас'),
        ),
        migrations.AlterField(
            model_name='supplierbrandalias',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='supplierbrandalias',
            name='priority',
            field=models.IntegerField(default=100, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='supplierbrandalias',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_aliases', to='supplier_imports.importsource', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='supplierbrandalias',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_aliases', to='pricing.supplier', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='supplierbrandalias',
            name='supplier_brand_alias',
            field=models.CharField(max_length=180, verbose_name='Алиас поставщика'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='article',
            field=models.CharField(blank=True, max_length=128, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='article_normalization_trace',
            field=models.JSONField(blank=True, default=list, verbose_name='Трейс нормализации артикула'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_offers', to='supplier_imports.importartifact', verbose_name='Артефакт'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='brand_name',
            field=models.CharField(blank=True, max_length=180, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='brand_normalization_trace',
            field=models.JSONField(blank=True, default=list, verbose_name='Трейс нормализации бренда'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='currency',
            field=models.CharField(default='UAH', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='external_sku',
            field=models.CharField(max_length=128, verbose_name='Внешний SKU'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='ignored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда проигнорировано'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='Валиден'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='last_matched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее сопоставление'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='lead_time_days',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Срок поставки (дней)'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='match_candidate_product_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Кандидаты сопоставления'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='match_reason',
            field=models.CharField(blank=True, choices=[('brand_conflict', 'Конфликт бренда'), ('article_conflict', 'Конфликт артикула'), ('ambiguous_match', 'Неоднозначное совпадение'), ('missing_brand', 'Не указан бренд'), ('missing_article', 'Не указан артикул')], db_index=True, max_length=64, verbose_name='Причина сопоставления'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='match_status',
            field=models.CharField(choices=[('unmatched', 'Не сопоставлен'), ('auto_matched', 'Сопоставлен автоматически'), ('manual_match_required', 'Требуется ручное сопоставление'), ('manually_matched', 'Сопоставлен вручную'), ('ignored', 'Игнорирован')], db_index=True, default='unmatched', max_length=32, verbose_name='Статус сопоставления'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='matched_manually_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда сопоставлено вручную'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='matched_manually_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manually_matched_raw_offers', to=settings.AUTH_USER_MODEL, verbose_name='Кем сопоставлено вручную'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='matched_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_supplier_offers', to='catalog.product', verbose_name='Сопоставленный товар'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='matching_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Попытки сопоставления'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='normalized_article',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Нормализованный артикул'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='normalized_brand',
            field=models.CharField(blank=True, db_index=True, max_length=180, verbose_name='Нормализованный бренд'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Сырой payload'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='row_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер строки'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_offers', to='supplier_imports.importrun', verbose_name='Запуск'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='skip_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина пропуска'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_offers', to='supplier_imports.importsource', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='stock_qty',
            field=models.IntegerField(default=0, verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_offers', to='pricing.supplier', verbose_name='Поставщик'),
        ),
    ]
