# Generated by Django 6.0.4 on 2026-04-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_imports', '0004_alter_articlenormalizationrule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importrunquality',
            name='auto_matched_rows',
            field=models.PositiveIntegerField(default=0, verbose_name='Автосопоставленные строки'),
        ),
        migrations.AlterField(
            model_name='importrunquality',
            name='conflict_rows',
            field=models.PositiveIntegerField(default=0, verbose_name='Конфликтные строки'),
        ),
        migrations.AlterField(
            model_name='importrunquality',
            name='error_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Доля ошибок'),
        ),
        migrations.AlterField(
            model_name='importrunquality',
            name='error_rate_delta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Изменение доли ошибок'),
        ),
        migrations.AlterField(
            model_name='importrunquality',
            name='error_rows',
            field=models.PositiveIntegerField(default=0, verbose_name='Строки с ошибками'),
        ),
        migrations.AlterField(
            model_name='importrunquality',
            name='flags',
            field=models.JSONField(blank=True, default=list, verbose_name='Флаги'),
        ),
        migrations.AlterField(
            model_name='importrunquality',
            name='ignored_rows',
            field=models.PositiveIntegerField(default=0, verbose_name='Игнорированные строки'),
        ),
        migrations.AlterField(
            model_name='importrunquality',
            name='manual_matched_rows',
            field=models.PositiveIntegerField(default=0, verbose_name='Сопоставленные вручную строки'),
        ),
        migrations.AlterField(
            model_name='importrunquality',
            name='match_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Доля сопоставления'),
        ),
        migrations.AlterField(
            model_name='importrunquality',
            name='match_rate_delta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Изменение доли сопоставления'),
        ),
        migrations.AlterField(
            model_name='importrunquality',
            name='matched_rows',
            field=models.PositiveIntegerField(default=0, verbose_name='Сопоставленные строки'),
        ),
        migrations.AlterField(
            model_name='importrunquality',
            name='summary',
            field=models.JSONField(blank=True, default=dict, verbose_name='Сводка'),
        ),
        migrations.AlterField(
            model_name='importrunquality',
            name='total_rows',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего строк'),
        ),
        migrations.AlterField(
            model_name='importrunquality',
            name='unmatched_rows',
            field=models.PositiveIntegerField(default=0, verbose_name='Несопоставленные строки'),
        ),
    ]
