# Generated by Codex on 2026-04-12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pricing", "0004_alter_currencyrate_options_and_more"),
        ("supplier_imports", "0005_alter_importrunquality_auto_matched_rows_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierIntegration",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("login", models.CharField(blank=True, max_length=255, verbose_name="Логин")),
                ("password", models.CharField(blank=True, max_length=255, verbose_name="Пароль")),
                ("browser_fingerprint", models.CharField(blank=True, default="svom-backoffice", max_length=128, verbose_name="Подпись клиента")),
                ("access_token", models.TextField(blank=True, verbose_name="Access token")),
                ("refresh_token", models.TextField(blank=True, verbose_name="Refresh token")),
                ("access_token_expires_at", models.DateTimeField(blank=True, null=True, verbose_name="Access token действует до")),
                ("refresh_token_expires_at", models.DateTimeField(blank=True, null=True, verbose_name="Refresh token действует до")),
                ("token_obtained_at", models.DateTimeField(blank=True, null=True, verbose_name="Токен получен")),
                ("last_token_refresh_at", models.DateTimeField(blank=True, null=True, verbose_name="Последнее обновление токена")),
                ("last_token_error_at", models.DateTimeField(blank=True, null=True, verbose_name="Последняя ошибка токена")),
                ("last_token_error_message", models.TextField(blank=True, verbose_name="Текст ошибки токена")),
                ("credentials_updated_at", models.DateTimeField(blank=True, null=True, verbose_name="Когда обновлены credentials")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="Интеграция включена")),
                ("last_request_at", models.DateTimeField(blank=True, null=True, verbose_name="Последний запрос к API")),
                ("next_allowed_request_at", models.DateTimeField(blank=True, null=True, verbose_name="Следующий разрешенный запрос")),
                ("last_successful_import_at", models.DateTimeField(blank=True, null=True, verbose_name="Последний успешный импорт")),
                ("last_failed_import_at", models.DateTimeField(blank=True, null=True, verbose_name="Последний неуспешный импорт")),
                ("last_import_error_message", models.TextField(blank=True, verbose_name="Текст последней ошибки импорта")),
                ("last_connection_check_at", models.DateTimeField(blank=True, null=True, verbose_name="Последняя проверка подключения")),
                ("last_connection_status", models.CharField(blank=True, default="", max_length=32, verbose_name="Статус подключения")),
                ("last_brands_import_at", models.DateTimeField(blank=True, null=True, verbose_name="Последний импорт брендов")),
                ("last_brands_import_count", models.PositiveIntegerField(default=0, verbose_name="Количество брендов последнего импорта")),
                ("last_brands_import_error_at", models.DateTimeField(blank=True, null=True, verbose_name="Последняя ошибка импорта брендов")),
                ("last_brands_import_error_message", models.TextField(blank=True, verbose_name="Текст ошибки импорта брендов")),
                (
                    "source",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="integration",
                        to="supplier_imports.importsource",
                        verbose_name="Источник импорта",
                    ),
                ),
                (
                    "supplier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="integration",
                        to="pricing.supplier",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Интеграция поставщика",
                "verbose_name_plural": "Интеграции поставщиков",
                "ordering": ("supplier__name",),
            },
        ),
    ]
