# Generated by Django 6.0.4 on 2026-04-12 15:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_alter_currencyrate_options_and_more'),
        ('supplier_imports', '0006_supplierintegration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPriceList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('generating', 'Генерируется'), ('ready', 'Готов'), ('downloaded', 'Скачан'), ('imported', 'Импортирован'), ('failed', 'Ошибка')], db_index=True, default='generating', max_length=24, verbose_name='Статус')),
                ('request_mode', models.CharField(blank=True, default='local', max_length=32, verbose_name='Режим запроса')),
                ('remote_id', models.CharField(blank=True, default='', max_length=128, verbose_name='ID прайса у поставщика')),
                ('remote_token', models.CharField(blank=True, default='', max_length=255, verbose_name='Токен прайса у поставщика')),
                ('remote_status', models.CharField(blank=True, default='', max_length=64, verbose_name='Статус прайса у поставщика')),
                ('requested_format', models.CharField(blank=True, default='', max_length=16, verbose_name='Запрошенный формат')),
                ('original_format', models.CharField(blank=True, default='', max_length=16, verbose_name='Исходный формат')),
                ('locale', models.CharField(blank=True, default='', max_length=16, verbose_name='Локаль')),
                ('is_in_stock', models.BooleanField(default=True, verbose_name='Только в наличии')),
                ('show_scancode', models.BooleanField(default=False, verbose_name='Показывать штрихкод')),
                ('utr_article', models.BooleanField(default=False, verbose_name='Показывать артикул UTR')),
                ('visible_brands', models.JSONField(blank=True, default=list, verbose_name='Выбранные бренды')),
                ('categories', models.JSONField(blank=True, default=list, verbose_name='Выбранные категории')),
                ('models_filter', models.JSONField(blank=True, default=list, verbose_name='Выбранные модели')),
                ('source_file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя файла источника')),
                ('source_file_path', models.CharField(blank=True, default='', max_length=1024, verbose_name='Путь к исходному файлу')),
                ('downloaded_file_path', models.CharField(blank=True, default='', max_length=1024, verbose_name='Путь скачанного файла')),
                ('file_size_label', models.CharField(blank=True, default='', max_length=64, verbose_name='Размер файла (текст)')),
                ('file_size_bytes', models.BigIntegerField(default=0, verbose_name='Размер файла (байты)')),
                ('price_columns', models.JSONField(blank=True, default=list, verbose_name='Колонки цен')),
                ('warehouse_columns', models.JSONField(blank=True, default=list, verbose_name='Колонки складов')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='Количество строк')),
                ('requested_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда запрошен')),
                ('expected_ready_at', models.DateTimeField(blank=True, null=True, verbose_name='Ожидаемая готовность')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда сформирован')),
                ('downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда скачан')),
                ('imported_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда импортирован')),
                ('last_error_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда произошла последняя ошибка')),
                ('last_error_message', models.TextField(blank=True, verbose_name='Текст последней ошибки')),
                ('request_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload запроса')),
                ('response_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload ответа')),
                ('imported_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_lists', to='supplier_imports.importrun', verbose_name='Запуск импорта')),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_lists', to='supplier_imports.supplierintegration', verbose_name='Интеграция')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='supplier_imports.importsource', verbose_name='Источник')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='pricing.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Прайс поставщика',
                'verbose_name_plural': 'Прайсы поставщиков',
                'ordering': ('-created_at',),
            },
        ),
    ]
