# Generated by Django 6.0.4 on 2026-04-14 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_backfill_product_utr_detail_id"),
        ("supplier_imports", "0007_supplierpricelist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierrawoffer",
            name="category_mapped_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Когда сопоставлена категория"),
        ),
        migrations.AddField(
            model_name="supplierrawoffer",
            name="category_mapped_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category_mapped_raw_offers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кем сопоставлена категория",
            ),
        ),
        migrations.AddField(
            model_name="supplierrawoffer",
            name="category_mapping_confidence",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=4,
                null=True,
                verbose_name="Уверенность сопоставления категории",
            ),
        ),
        migrations.AddField(
            model_name="supplierrawoffer",
            name="category_mapping_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manual", "Ручной выбор"),
                    ("from_product", "Из связанного товара"),
                    ("supplier_category_exact", "Точное совпадение категории поставщика"),
                    ("supplier_category_fuzzy", "Похожая категория поставщика"),
                    ("name_tokens", "Совпадение по названию товара"),
                    ("ambiguous_category_signal", "Неоднозначный сигнал категории поставщика"),
                    ("ambiguous_name_signal", "Неоднозначный сигнал по названию"),
                    ("no_category_signal", "Нет сигнала категории"),
                    ("low_confidence", "Низкая уверенность"),
                    ("unset", "Сопоставление снято"),
                ],
                db_index=True,
                default="",
                max_length=64,
                verbose_name="Причина сопоставления категории",
            ),
        ),
        migrations.AddField(
            model_name="supplierrawoffer",
            name="category_mapping_status",
            field=models.CharField(
                choices=[
                    ("unmapped", "Не сопоставлен"),
                    ("auto_mapped", "Сопоставлен автоматически"),
                    ("manual_mapped", "Сопоставлен вручную"),
                    ("needs_review", "Требуется проверка"),
                ],
                db_index=True,
                default="unmapped",
                max_length=24,
                verbose_name="Статус сопоставления категории",
            ),
        ),
        migrations.AddField(
            model_name="supplierrawoffer",
            name="mapped_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="raw_offer_category_mappings",
                to="catalog.category",
                verbose_name="Сопоставленная категория",
            ),
        ),
    ]
