# Generated by Django 6.0.4 on 2026-04-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_imports', '0008_supplierrawoffer_category_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierrawoffer',
            name='category_mapping_reason',
            field=models.CharField(blank=True, choices=[('manual', 'Ручной выбор'), ('from_product', 'Из связанного товара'), ('supplier_category_exact', 'Точное совпадение категории поставщика'), ('supplier_category_fuzzy', 'Похожая категория поставщика'), ('name_tokens', 'Совпадение по названию товара'), ('ambiguous_category_signal', 'Неоднозначный сигнал категории поставщика'), ('ambiguous_name_signal', 'Неоднозначный сигнал по названию'), ('no_category_signal', 'Нет сигнала категории'), ('low_confidence', 'Низкая уверенность'), ('unset', 'Сопоставление снято'), ('force_signal_learning', 'Принудительно из накопленных сигналов категории'), ('force_title_signature', 'Принудительно по сигнатуре названия'), ('force_brand_cluster', 'Принудительно по брендовому кластеру'), ('force_token_cluster', 'Принудительно по токенам названия'), ('force_relaxed_name', 'Принудительно по ослабленному совпадению названия'), ('force_supplier_default', 'Принудительно по категории поставщика по умолчанию'), ('force_global_default', 'Принудительно по глобальной категории по умолчанию'), ('force_guardrail_remap', 'Переназначено guardrail-правилом'), ('force_guardrail_review', 'Оставлено на проверку guardrail-правилом')], db_index=True, default='', max_length=64, verbose_name='Причина сопоставления категории'),
        ),
    ]
