# Generated by Django 6.0.4 on 2026-04-11 13:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('title_uk', models.CharField(blank=True, max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('subtitle_uk', models.CharField(blank=True, max_length=500)),
                ('subtitle_ru', models.CharField(blank=True, max_length=500)),
                ('subtitle_en', models.CharField(blank=True, max_length=500)),
                ('desktop_image', models.ImageField(upload_to='marketing/hero/desktop/')),
                ('mobile_image', models.ImageField(upload_to='marketing/hero/mobile/')),
                ('cta_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Hero slide',
                'verbose_name_plural': 'Hero slides',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroSliderSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default='default', max_length=32, unique=True)),
                ('autoplay_enabled', models.BooleanField(default=True)),
                ('transition_interval_ms', models.PositiveIntegerField(default=5000)),
                ('transition_speed_ms', models.PositiveIntegerField(default=600)),
                ('max_active_slides', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Hero slider settings',
                'verbose_name_plural': 'Hero slider settings',
            },
        ),
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('title_uk', models.CharField(blank=True, max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('description_uk', models.CharField(blank=True, max_length=500)),
                ('description_ru', models.CharField(blank=True, max_length=500)),
                ('description_en', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to='marketing/promo/')),
                ('target_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Promo banner',
                'verbose_name_plural': 'Promo banners',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromoBannerSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default='default', max_length=32, unique=True)),
                ('autoplay_enabled', models.BooleanField(default=True)),
                ('transition_interval_ms', models.PositiveIntegerField(default=4500)),
                ('transition_speed_ms', models.PositiveIntegerField(default=700)),
                ('max_active_banners', models.PositiveSmallIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Promo banner settings',
                'verbose_name_plural': 'Promo banner settings',
            },
        ),
    ]
