# Generated by Django 6.0.4 on 2026-04-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'Слайд hero', 'verbose_name_plural': 'Слайды hero'},
        ),
        migrations.AlterModelOptions(
            name='heroslidersettings',
            options={'verbose_name': 'Настройки hero-слайдера', 'verbose_name_plural': 'Настройки hero-слайдера'},
        ),
        migrations.AlterModelOptions(
            name='promobanner',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'Промо-баннер', 'verbose_name_plural': 'Промо-баннеры'},
        ),
        migrations.AlterModelOptions(
            name='promobannersettings',
            options={'verbose_name': 'Настройки промо-баннеров', 'verbose_name_plural': 'Настройки промо-баннеров'},
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='cta_url',
            field=models.URLField(blank=True, verbose_name='Ссылка CTA'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='desktop_image',
            field=models.ImageField(upload_to='marketing/hero/desktop/', verbose_name='Изображение для десктопа'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='mobile_image',
            field=models.ImageField(upload_to='marketing/hero/mobile/', verbose_name='Изображение для мобильных'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='Подзаголовок (en)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=500, verbose_name='Подзаголовок (ru)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle_uk',
            field=models.CharField(blank=True, max_length=500, verbose_name='Подзаголовок (uk)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (en)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (ru)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (uk)'),
        ),
        migrations.AlterField(
            model_name='heroslidersettings',
            name='autoplay_enabled',
            field=models.BooleanField(default=True, verbose_name='Автопрокрутка включена'),
        ),
        migrations.AlterField(
            model_name='heroslidersettings',
            name='code',
            field=models.CharField(default='default', max_length=32, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='heroslidersettings',
            name='max_active_slides',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Максимум активных слайдов'),
        ),
        migrations.AlterField(
            model_name='heroslidersettings',
            name='transition_interval_ms',
            field=models.PositiveIntegerField(default=5000, verbose_name='Интервал перехода, мс'),
        ),
        migrations.AlterField(
            model_name='heroslidersettings',
            name='transition_speed_ms',
            field=models.PositiveIntegerField(default=600, verbose_name='Скорость перехода, мс'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='description_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='Описание (en)'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='description_ru',
            field=models.CharField(blank=True, max_length=500, verbose_name='Описание (ru)'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='description_uk',
            field=models.CharField(blank=True, max_length=500, verbose_name='Описание (uk)'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='image',
            field=models.ImageField(upload_to='marketing/promo/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='target_url',
            field=models.URLField(blank=True, verbose_name='Целевая ссылка'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (en)'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (ru)'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='title_uk',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (uk)'),
        ),
        migrations.AlterField(
            model_name='promobannersettings',
            name='autoplay_enabled',
            field=models.BooleanField(default=True, verbose_name='Автопрокрутка включена'),
        ),
        migrations.AlterField(
            model_name='promobannersettings',
            name='code',
            field=models.CharField(default='default', max_length=32, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='promobannersettings',
            name='max_active_banners',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Максимум активных баннеров'),
        ),
        migrations.AlterField(
            model_name='promobannersettings',
            name='transition_interval_ms',
            field=models.PositiveIntegerField(default=4500, verbose_name='Интервал перехода, мс'),
        ),
        migrations.AlterField(
            model_name='promobannersettings',
            name='transition_speed_ms',
            field=models.PositiveIntegerField(default=700, verbose_name='Скорость перехода, мс'),
        ),
    ]
