# Generated by Django 6.0.4 on 2026-04-22 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0002_alter_heroslide_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterSettings",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(default="default", max_length=32, unique=True, verbose_name="Код")),
                (
                    "working_hours",
                    models.CharField(default="ПН, ВТ, СР, ЧТ, ПТ, СБ 10:00-17:00", max_length=255, verbose_name="Время работы"),
                ),
                ("phone", models.CharField(default="+38(099)897-94-67", max_length=64, verbose_name="Телефон")),
            ],
            options={
                "verbose_name": "Настройки футера",
                "verbose_name_plural": "Настройки футера",
            },
        ),
    ]
