# Generated by Django 6.0.4 on 2026-04-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0003_footersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="promobanner",
            name="ends_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Показ до"),
        ),
        migrations.AddField(
            model_name="promobanner",
            name="starts_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Показ с"),
        ),
        migrations.AddField(
            model_name="promobannersettings",
            name="transition_effect",
            field=models.CharField(default="fade", max_length=32, verbose_name="Эффект смены"),
        ),
    ]
