# Generated by Django 6.0.4 on 2026-04-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0004_promobanner_schedule_and_transition_effect"),
    ]

    operations = [
        migrations.AddField(
            model_name="heroslidersettings",
            name="transition_effect",
            field=models.CharField(default="crossfade", max_length=32, verbose_name="Эффект смены"),
        ),
    ]
