# Generated by Django 6.0.4 on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0005_heroslidersettings_transition_effect"),
    ]

    operations = [
        migrations.AddField(
            model_name="footersettings",
            name="phone_format",
            field=models.CharField(
                choices=[("mobile", "Мобильный"), ("toll_free_0800", "0 (800) XXX-XXX")],
                default="mobile",
                max_length=24,
                verbose_name="Формат телефона",
            ),
        ),
    ]
