# Generated by Django 6.0.4 on 2026-04-24 11:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleEventSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_name', models.CharField(max_length=120, unique=True, verbose_name='Event name')),
                ('label', models.CharField(max_length=180, verbose_name='Label')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Google event setting',
                'verbose_name_plural': 'Google event settings',
                'ordering': ('event_name',),
            },
        ),
        migrations.CreateModel(
            name='GoogleIntegrationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default='default', max_length=32, unique=True)),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Google integration enabled')),
                ('ga4_measurement_id', models.CharField(blank=True, default='', max_length=64, verbose_name='GA4 Measurement ID')),
                ('gtm_container_id', models.CharField(blank=True, default='', max_length=64, verbose_name='GTM Container ID')),
                ('search_console_verification_token', models.CharField(blank=True, default='', max_length=512, verbose_name='Search Console verification token')),
                ('google_site_verification_meta', models.CharField(blank=True, default='', max_length=512, verbose_name='Google site verification meta')),
                ('consent_mode_enabled', models.BooleanField(default=False, verbose_name='Consent mode enabled')),
                ('ecommerce_events_enabled', models.BooleanField(default=True, verbose_name='Ecommerce events enabled')),
                ('debug_mode', models.BooleanField(default=False, verbose_name='Debug mode')),
                ('anonymize_ip', models.BooleanField(default=True, verbose_name='Anonymize IP')),
            ],
            options={
                'verbose_name': 'Google integration settings',
                'verbose_name_plural': 'Google integration settings',
            },
        ),
        migrations.CreateModel(
            name='SeoSiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default='default', max_length=32, unique=True)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='SEO включено')),
                ('default_meta_title_uk', models.CharField(blank=True, default='', max_length=255, verbose_name='Default meta title (UK)')),
                ('default_meta_title_ru', models.CharField(blank=True, default='', max_length=255, verbose_name='Default meta title (RU)')),
                ('default_meta_title_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Default meta title (EN)')),
                ('default_meta_description_uk', models.TextField(blank=True, default='', verbose_name='Default meta description (UK)')),
                ('default_meta_description_ru', models.TextField(blank=True, default='', verbose_name='Default meta description (RU)')),
                ('default_meta_description_en', models.TextField(blank=True, default='', verbose_name='Default meta description (EN)')),
                ('default_og_title_uk', models.CharField(blank=True, default='', max_length=255, verbose_name='Default OG title (UK)')),
                ('default_og_title_ru', models.CharField(blank=True, default='', max_length=255, verbose_name='Default OG title (RU)')),
                ('default_og_title_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Default OG title (EN)')),
                ('default_og_description_uk', models.TextField(blank=True, default='', verbose_name='Default OG description (UK)')),
                ('default_og_description_ru', models.TextField(blank=True, default='', verbose_name='Default OG description (RU)')),
                ('default_og_description_en', models.TextField(blank=True, default='', verbose_name='Default OG description (EN)')),
                ('default_robots_directive', models.CharField(blank=True, default='index,follow', max_length=64, verbose_name='Default robots directive')),
                ('canonical_base_url', models.URLField(blank=True, default='', verbose_name='Canonical base URL')),
                ('sitemap_enabled', models.BooleanField(default=True, verbose_name='Sitemap enabled')),
                ('product_sitemap_enabled', models.BooleanField(default=True, verbose_name='Product sitemap enabled')),
                ('category_sitemap_enabled', models.BooleanField(default=True, verbose_name='Category sitemap enabled')),
                ('brand_sitemap_enabled', models.BooleanField(default=True, verbose_name='Brand sitemap enabled')),
                ('sitemap_last_rebuild_at', models.DateTimeField(blank=True, null=True, verbose_name='Sitemap last rebuild at')),
                ('robots_txt', models.TextField(blank=True, default='', verbose_name='Robots.txt')),
            ],
            options={
                'verbose_name': 'SEO site settings',
                'verbose_name_plural': 'SEO site settings',
            },
        ),
        migrations.CreateModel(
            name='SeoMetaOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=500, verbose_name='Path')),
                ('locale', models.CharField(choices=[('uk', 'Ukrainian'), ('ru', 'Russian'), ('en', 'English')], max_length=2, verbose_name='Locale')),
                ('meta_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, default='', verbose_name='Meta description')),
                ('h1', models.CharField(blank=True, default='', max_length=255, verbose_name='H1')),
                ('canonical_url', models.URLField(blank=True, default='', verbose_name='Canonical URL')),
                ('robots_directive', models.CharField(blank=True, default='', max_length=64, verbose_name='Robots directive')),
                ('og_title', models.CharField(blank=True, default='', max_length=255, verbose_name='OG title')),
                ('og_description', models.TextField(blank=True, default='', verbose_name='OG description')),
                ('og_image_url', models.URLField(blank=True, default='', verbose_name='OG image URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'SEO meta override',
                'verbose_name_plural': 'SEO meta overrides',
                'indexes': [models.Index(fields=['path', 'locale', 'is_active'], name='seo_override_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('path', 'locale'), name='seo_meta_override_path_locale_uniq')],
            },
        ),
        migrations.CreateModel(
            name='SeoMetaTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('product', 'Product'), ('category', 'Category'), ('brand', 'Brand'), ('page', 'Page')], max_length=24, verbose_name='Entity type')),
                ('locale', models.CharField(choices=[('uk', 'Ukrainian'), ('ru', 'Russian'), ('en', 'English')], max_length=2, verbose_name='Locale')),
                ('title_template', models.CharField(blank=True, default='', max_length=255, verbose_name='Title template')),
                ('description_template', models.TextField(blank=True, default='', verbose_name='Description template')),
                ('h1_template', models.CharField(blank=True, default='', max_length=255, verbose_name='H1 template')),
                ('og_title_template', models.CharField(blank=True, default='', max_length=255, verbose_name='OG title template')),
                ('og_description_template', models.TextField(blank=True, default='', verbose_name='OG description template')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'SEO meta template',
                'verbose_name_plural': 'SEO meta templates',
                'indexes': [models.Index(fields=['entity_type', 'locale', 'is_active'], name='seo_template_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'locale'), name='seo_meta_template_entity_locale_uniq')],
            },
        ),
    ]
