export type BackofficeCatalogBrand = {
  id: string;
  name: string;
  slug: string;
  country: string;
  description: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
};

export type BackofficeAutoDbSupplierBrand = {
  id: number;
  name: string;
  matchcode: string;
  article_count: number;
  is_active: boolean;
};

export type BackofficeCatalogCategory = {
  id: string;
  name: string;
  name_uk: string;
  name_ru: string;
  name_en: string;
  slug: string;
  source: string;
  autodb_prd_id: number | null;
  parent: string | null;
  parent_name: string;
  description: string;
  is_active: boolean;
  show_in_header: boolean;
  created_at: string;
  updated_at: string;
};

export type BackofficeCatalogProduct = {
  id: string;
  sku: string;
  svom_sku?: string | null;
  product_display_sku?: string;
  internal_import_key?: string;
  article: string;
  name: string;
  display_name?: string;
  display_name_source?: string;
  name_uk?: string;
  name_ru?: string;
  name_en?: string;
  slug: string;
  brand: string;
  brand_name: string;
  current_brand_name?: string;
  display_brand?: string;
  brand_source?: string;
  autodb_supplier_id?: number | null;
  autodb_supplier_name?: string;
  raw_supplier_brand?: string;
  category: string;
  category_name: string;
  catalog_source?: string;
  name_source?: string;
  name_translation_status?: string;
  name_manually_locked?: boolean;
  autodb_article_key?: string;
  name_quality_flags?: string[];
  raw_supplier_name?: string;
  final_price: string | null;
  currency: string | null;
  price_updated_at: string | null;
  supplier_price: string | null;
  supplier_currency: string | null;
  supplier_price_levels: Array<{
    key: string;
    label: string;
    value: string;
    currency: string;
    is_primary: boolean;
    order: number;
  }>;
  applied_markup_percent: string | null;
  applied_markup_policy_name: string;
  applied_markup_policy_scope: string;
  warehouse_segments: Array<{
    key: string;
    value: string;
    source_code: string;
  }>;
  supplier_sku: string;
  supplier_offer_seen_at: string | null;
  selected_offer_supplier_code?: string;
  selected_offer_supplier_sku?: string;
  selected_offer_purchase_price?: string | null;
  selected_offer_stock_qty?: number | null;
  selected_offer_raw_article?: string;
  selected_offer_raw_brand?: string;
  supplier_code?: string;
  supplier_codes?: string[];
  primary_supplier_code?: string;
  has_product_price?: boolean;
  has_available_offer?: boolean;
  productprice_status?: "has_price" | "no_product_price" | "no_available_offer" | "invalid_offer";
  productprice_status_reason?: string;
  product_is_active?: boolean;
  is_public?: boolean;
  published_at?: string | null;
  autodb_link_status?: "linked" | "unlinked" | "trusted" | "suspicious" | "needs_review";
  compatibility_available?: boolean;
  warehouse_summary?: {
    warehouse_total_count: number;
    warehouse_nonzero_count: number;
    stock_qty_total: number;
    supplier_offer_stock_sum: number;
  };
  price_tooltip_summary?: {
    final_price?: string | null;
    selected_supplier_price?: string | null;
    utr_price?: string | null;
    gpl_rrc_price?: string | null;
    markup_percent?: string | null;
    pricing_policy?: string | null;
    updated_at?: string | null;
  };
  short_description: string;
  description: string;
  is_active: boolean;
  is_featured: boolean;
  is_new: boolean;
  is_bestseller: boolean;
  created_at: string;
  updated_at: string;
};
