from django.urls import path

from apps.backoffice.api.views import (
    ArticleRuleListCreateAPIView,
    ArticleRuleRetrieveUpdateAPIView,
    BackofficeAutocatalogFilterOptionsAPIView,
    BackofficeAutocatalogListAPIView,
    BackofficeSummaryAPIView,
    BackofficeCatalogBrandListCreateAPIView,
    BackofficeCatalogBrandRetrieveUpdateDestroyAPIView,
    BackofficeCatalogCategoryListCreateAPIView,
    BackofficeCatalogCategoryRetrieveUpdateDestroyAPIView,
    BackofficeCatalogProductListCreateAPIView,
    BackofficeCatalogProductRetrieveUpdateDestroyAPIView,
    BackofficeProductFitmentListCreateAPIView,
    BackofficeProductFitmentRetrieveUpdateDestroyAPIView,
    BrandAliasListCreateAPIView,
    BrandAliasRetrieveUpdateAPIView,
    BulkAwaitingProcurementActionAPIView,
    BulkDeleteOrdersActionAPIView,
    BulkConfirmOrdersActionAPIView,
    BulkMoveProductsCategoryActionAPIView,
    CancelOrderActionAPIView,
    ConfirmOrderActionAPIView,
    DeleteOrderActionAPIView,
    ImportAllActionAPIView,
    ImportRowErrorListAPIView,
    ImportQualityCompareAPIView,
    ImportQualityDetailAPIView,
    ImportQualityListAPIView,
    ImportQualitySummaryAPIView,
    ImportRunDetailAPIView,
    ImportRunListAPIView,
    ImportScheduleListAPIView,
    ImportScheduleUpdateAPIView,
    ImportSourceListAPIView,
    NovaPoshtaCounterpartyDetailsLookupAPIView,
    NovaPoshtaCounterpartiesLookupAPIView,
    NovaPoshtaDeliveryDateLookupAPIView,
    NovaPoshtaPackingsLookupAPIView,
    NovaPoshtaSenderProfileListCreateAPIView,
    NovaPoshtaSenderProfileRetrieveUpdateDestroyAPIView,
    NovaPoshtaSenderProfileValidateAPIView,
    NovaPoshtaSettlementsLookupAPIView,
    NovaPoshtaStreetsLookupAPIView,
    NovaPoshtaTimeIntervalsLookupAPIView,
    NovaPoshtaWarehousesLookupAPIView,
    OrderNovaPoshtaWaybillCreateAPIView,
    OrderNovaPoshtaWaybillDeleteAPIView,
    OrderNovaPoshtaWaybillDetailAPIView,
    OrderNovaPoshtaWaybillPrintAPIView,
    OrderNovaPoshtaWaybillSyncAPIView,
    OrderNovaPoshtaWaybillUpdateAPIView,
    MarkAwaitingProcurementActionAPIView,
    GplCancelOrderAPIView,
    GplCreateOrderAPIView,
    GplOrderPayloadPreviewAPIView,
    GplSupplierOrderDetailAPIView,
    GplSupplierOrdersListAPIView,
    OrderItemSupplierOverrideAPIView,
    OrderItemSupplierRecommendationAPIView,
    OrderOperationalDetailAPIView,
    OrderOperationalListAPIView,
    BackofficeMonobankSettingsAPIView,
    BackofficeLiqPayConnectionTestAPIView,
    BackofficeLiqPaySettingsAPIView,
    BackofficeLoyaltyCustomerLookupAPIView,
    BackofficeLoyaltyIssueAPIView,
    BackofficeLoyaltyIssuanceListAPIView,
    BackofficeLoyaltyStatsAPIView,
    BackofficeNovaPaySettingsAPIView,
    BackofficeMonobankConnectionTestAPIView,
    BackofficeMonobankCurrencyAPIView,
    BackofficeNovaPayConnectionTestAPIView,
    BackofficeOrderPaymentMonobankActionAPIView,
    BackofficeOrderPaymentRefreshAPIView,
    BackofficeRbacMetaAPIView,
    BackofficeUserActivateAPIView,
    BackofficeUserDeactivateAPIView,
    BackofficeUserListCreateAPIView,
    BackofficeUserRetrieveUpdateAPIView,
    BackofficeGroupListCreateAPIView,
    BackofficeGroupRetrieveUpdateAPIView,
    ProductPriceOperationalListAPIView,
    PricingCategoryImpactAPIView,
    PricingCategoryMarkupAPIView,
    PricingControlPanelAPIView,
    PricingGlobalMarkupAPIView,
    PricingRecalculateAPIView,
    ProcurementItemRecommendationAPIView,
    ProcurementSuggestionsListAPIView,
    ReindexProductsActionAPIView,
    RepriceAfterImportActionAPIView,
    ReadyToShipOrderActionAPIView,
    ReserveOrderItemsActionAPIView,
    RunImportSourceActionAPIView,
    SupplierOfferOperationalListAPIView,
    CategoryMappingCategorySearchAPIView,
    SupplierRawOfferCategoryMappingAPIView,
    SupplierConnectionCheckAPIView,
    SupplierCooldownAPIView,
    SupplierErrorsListAPIView,
    SupplierPriceListDeleteAPIView,
    SupplierImportRunAPIView,
    SupplierPriceListDownloadAPIView,
    SupplierPriceListImportAPIView,
    SupplierPriceListListAPIView,
    SupplierPriceListParamsAPIView,
    SupplierPriceListRequestAPIView,
    SupplierPublishMappedProductsAPIView,
    SupplierPricesListAPIView,
    SupplierPricesSyncAPIView,
    SupplierRunsListAPIView,
    SupplierTokenObtainAPIView,
    SupplierTokenRefreshAPIView,
    SupplierWorkspaceDetailAPIView,
    SupplierWorkspaceListAPIView,
    SupplierWorkspaceSettingsAPIView,
    SupplierRawOfferListAPIView,
    UtrBrandsImportAPIView,
    BackofficeVehicleMakeListCreateAPIView,
    BackofficeVehicleMakeRetrieveUpdateDestroyAPIView,
    BackofficeVehicleModelListCreateAPIView,
    BackofficeVehicleModelRetrieveUpdateDestroyAPIView,
    BackofficeVehicleGenerationListCreateAPIView,
    BackofficeVehicleGenerationRetrieveUpdateDestroyAPIView,
    BackofficeVehicleEngineListCreateAPIView,
    BackofficeVehicleEngineRetrieveUpdateDestroyAPIView,
    BackofficeVehicleModificationListCreateAPIView,
    BackofficeVehicleModificationRetrieveUpdateDestroyAPIView,
)

app_name = "backoffice_api"

urlpatterns = [
    path("summary/", BackofficeSummaryAPIView.as_view(), name="summary"),
    path("import-sources/", ImportSourceListAPIView.as_view(), name="import-source-list"),
    path("import-schedules/", ImportScheduleListAPIView.as_view(), name="import-schedule-list"),
    path("import-schedules/<uuid:id>/", ImportScheduleUpdateAPIView.as_view(), name="import-schedule-update"),
    path("import-runs/", ImportRunListAPIView.as_view(), name="import-run-list"),
    path("import-runs/<uuid:id>/", ImportRunDetailAPIView.as_view(), name="import-run-detail"),
    path("import-errors/", ImportRowErrorListAPIView.as_view(), name="import-error-list"),
    path("brand-aliases/", BrandAliasListCreateAPIView.as_view(), name="brand-alias-list-create"),
    path("brand-aliases/<uuid:id>/", BrandAliasRetrieveUpdateAPIView.as_view(), name="brand-alias-update"),
    path("brands/", BackofficeCatalogBrandListCreateAPIView.as_view(), name="catalog-brand-list-create"),
    path("brands/<uuid:id>/", BackofficeCatalogBrandRetrieveUpdateDestroyAPIView.as_view(), name="catalog-brand-update"),
    path("categories/", BackofficeCatalogCategoryListCreateAPIView.as_view(), name="catalog-category-list-create"),
    path("categories/<uuid:id>/", BackofficeCatalogCategoryRetrieveUpdateDestroyAPIView.as_view(), name="catalog-category-update"),
    path("products/", BackofficeCatalogProductListCreateAPIView.as_view(), name="catalog-product-list-create"),
    path("products/<uuid:id>/", BackofficeCatalogProductRetrieveUpdateDestroyAPIView.as_view(), name="catalog-product-update"),
    path("vehicle-makes/", BackofficeVehicleMakeListCreateAPIView.as_view(), name="vehicle-make-list-create"),
    path("vehicle-makes/<uuid:id>/", BackofficeVehicleMakeRetrieveUpdateDestroyAPIView.as_view(), name="vehicle-make-update"),
    path("vehicle-models/", BackofficeVehicleModelListCreateAPIView.as_view(), name="vehicle-model-list-create"),
    path("vehicle-models/<uuid:id>/", BackofficeVehicleModelRetrieveUpdateDestroyAPIView.as_view(), name="vehicle-model-update"),
    path("vehicle-generations/", BackofficeVehicleGenerationListCreateAPIView.as_view(), name="vehicle-generation-list-create"),
    path(
        "vehicle-generations/<uuid:id>/",
        BackofficeVehicleGenerationRetrieveUpdateDestroyAPIView.as_view(),
        name="vehicle-generation-update",
    ),
    path("vehicle-engines/", BackofficeVehicleEngineListCreateAPIView.as_view(), name="vehicle-engine-list-create"),
    path("vehicle-engines/<uuid:id>/", BackofficeVehicleEngineRetrieveUpdateDestroyAPIView.as_view(), name="vehicle-engine-update"),
    path(
        "vehicle-modifications/",
        BackofficeVehicleModificationListCreateAPIView.as_view(),
        name="vehicle-modification-list-create",
    ),
    path(
        "vehicle-modifications/<uuid:id>/",
        BackofficeVehicleModificationRetrieveUpdateDestroyAPIView.as_view(),
        name="vehicle-modification-update",
    ),
    path("product-fitments/", BackofficeProductFitmentListCreateAPIView.as_view(), name="product-fitment-list-create"),
    path(
        "product-fitments/<uuid:id>/",
        BackofficeProductFitmentRetrieveUpdateDestroyAPIView.as_view(),
        name="product-fitment-update",
    ),
    path("autocatalog/", BackofficeAutocatalogListAPIView.as_view(), name="autocatalog-list"),
    path("autocatalog/filter-options/", BackofficeAutocatalogFilterOptionsAPIView.as_view(), name="autocatalog-filter-options"),
    path("article-rules/", ArticleRuleListCreateAPIView.as_view(), name="article-rule-list-create"),
    path("article-rules/<uuid:id>/", ArticleRuleRetrieveUpdateAPIView.as_view(), name="article-rule-update"),
    path("import-quality/summary/", ImportQualitySummaryAPIView.as_view(), name="import-quality-summary"),
    path("import-quality/runs/", ImportQualityListAPIView.as_view(), name="import-quality-list"),
    path("import-quality/runs/<uuid:run_id>/", ImportQualityDetailAPIView.as_view(), name="import-quality-detail"),
    path("import-quality/runs/<uuid:run_id>/compare/", ImportQualityCompareAPIView.as_view(), name="import-quality-compare"),
    path("raw-offers/", SupplierRawOfferListAPIView.as_view(), name="raw-offer-list"),
    path(
        "raw-offers/<uuid:raw_offer_id>/category-mapping/",
        SupplierRawOfferCategoryMappingAPIView.as_view(),
        name="raw-offer-category-mapping",
    ),
    path(
        "raw-offers/category-mapping/categories/",
        CategoryMappingCategorySearchAPIView.as_view(),
        name="raw-offer-category-search",
    ),
    path("supplier-offers/", SupplierOfferOperationalListAPIView.as_view(), name="supplier-offer-list"),
    path("suppliers/", SupplierWorkspaceListAPIView.as_view(), name="supplier-workspace-list"),
    path("suppliers/<slug:code>/workspace/", SupplierWorkspaceDetailAPIView.as_view(), name="supplier-workspace-detail"),
    path("suppliers/<slug:code>/settings/", SupplierWorkspaceSettingsAPIView.as_view(), name="supplier-workspace-settings"),
    path("suppliers/<slug:code>/token/obtain/", SupplierTokenObtainAPIView.as_view(), name="supplier-token-obtain"),
    path("suppliers/<slug:code>/token/refresh/", SupplierTokenRefreshAPIView.as_view(), name="supplier-token-refresh"),
    path("suppliers/<slug:code>/connection/check/", SupplierConnectionCheckAPIView.as_view(), name="supplier-connection-check"),
    path("suppliers/<slug:code>/import/run/", SupplierImportRunAPIView.as_view(), name="supplier-import-run"),
    path(
        "suppliers/<slug:code>/products/publish-mapped/",
        SupplierPublishMappedProductsAPIView.as_view(),
        name="supplier-publish-mapped-products",
    ),
    path("suppliers/<slug:code>/prices/sync/", SupplierPricesSyncAPIView.as_view(), name="supplier-prices-sync"),
    path("suppliers/<slug:code>/price-lists/", SupplierPriceListListAPIView.as_view(), name="supplier-price-list-list"),
    path("suppliers/<slug:code>/price-lists/params/", SupplierPriceListParamsAPIView.as_view(), name="supplier-price-list-params"),
    path("suppliers/<slug:code>/price-lists/request/", SupplierPriceListRequestAPIView.as_view(), name="supplier-price-list-request"),
    path(
        "suppliers/<slug:code>/price-lists/<uuid:price_list_id>/delete/",
        SupplierPriceListDeleteAPIView.as_view(),
        name="supplier-price-list-delete",
    ),
    path(
        "suppliers/<slug:code>/price-lists/<uuid:price_list_id>/download/",
        SupplierPriceListDownloadAPIView.as_view(),
        name="supplier-price-list-download",
    ),
    path(
        "suppliers/<slug:code>/price-lists/<uuid:price_list_id>/import/",
        SupplierPriceListImportAPIView.as_view(),
        name="supplier-price-list-import",
    ),
    path("suppliers/utr/brands/import/", UtrBrandsImportAPIView.as_view(), name="supplier-utr-brands-import"),
    path("suppliers/<slug:code>/prices/", SupplierPricesListAPIView.as_view(), name="supplier-prices-list"),
    path("suppliers/<slug:code>/runs/", SupplierRunsListAPIView.as_view(), name="supplier-runs-list"),
    path("suppliers/<slug:code>/errors/", SupplierErrorsListAPIView.as_view(), name="supplier-errors-list"),
    path("suppliers/<slug:code>/cooldown/", SupplierCooldownAPIView.as_view(), name="supplier-cooldown"),
    path("product-prices/", ProductPriceOperationalListAPIView.as_view(), name="product-price-list"),
    path("pricing/control-panel/", PricingControlPanelAPIView.as_view(), name="pricing-control-panel"),
    path("pricing/category-impact/", PricingCategoryImpactAPIView.as_view(), name="pricing-category-impact"),
    path("pricing/global-markup/", PricingGlobalMarkupAPIView.as_view(), name="pricing-global-markup"),
    path("pricing/category-markup/", PricingCategoryMarkupAPIView.as_view(), name="pricing-category-markup"),
    path("pricing/recalculate/", PricingRecalculateAPIView.as_view(), name="pricing-recalculate"),
    path("loyalty/issue/", BackofficeLoyaltyIssueAPIView.as_view(), name="loyalty-issue"),
    path("loyalty/issuances/", BackofficeLoyaltyIssuanceListAPIView.as_view(), name="loyalty-issuances"),
    path("loyalty/stats/", BackofficeLoyaltyStatsAPIView.as_view(), name="loyalty-stats"),
    path("loyalty/customers/", BackofficeLoyaltyCustomerLookupAPIView.as_view(), name="loyalty-customers"),
    path("nova-poshta/senders/", NovaPoshtaSenderProfileListCreateAPIView.as_view(), name="nova-poshta-sender-list-create"),
    path("nova-poshta/senders/<uuid:id>/", NovaPoshtaSenderProfileRetrieveUpdateDestroyAPIView.as_view(), name="nova-poshta-sender-update"),
    path("nova-poshta/senders/<uuid:id>/validate/", NovaPoshtaSenderProfileValidateAPIView.as_view(), name="nova-poshta-sender-validate"),
    path("orders/waybill/lookups/counterparty-details/", NovaPoshtaCounterpartyDetailsLookupAPIView.as_view(), name="order-waybill-lookup-counterparty-details"),
    path("orders/waybill/lookups/counterparties/", NovaPoshtaCounterpartiesLookupAPIView.as_view(), name="order-waybill-lookup-counterparties"),
    path("orders/waybill/lookups/packings/", NovaPoshtaPackingsLookupAPIView.as_view(), name="order-waybill-lookup-packings"),
    path("orders/waybill/lookups/delivery-date/", NovaPoshtaDeliveryDateLookupAPIView.as_view(), name="order-waybill-lookup-delivery-date"),
    path("orders/waybill/lookups/settlements/", NovaPoshtaSettlementsLookupAPIView.as_view(), name="order-waybill-lookup-settlements"),
    path("orders/waybill/lookups/streets/", NovaPoshtaStreetsLookupAPIView.as_view(), name="order-waybill-lookup-streets"),
    path("orders/waybill/lookups/time-intervals/", NovaPoshtaTimeIntervalsLookupAPIView.as_view(), name="order-waybill-lookup-time-intervals"),
    path("orders/waybill/lookups/warehouses/", NovaPoshtaWarehousesLookupAPIView.as_view(), name="order-waybill-lookup-warehouses"),
    path("orders/<uuid:order_id>/waybill/", OrderNovaPoshtaWaybillDetailAPIView.as_view(), name="order-waybill-detail"),
    path("orders/<uuid:order_id>/waybill/create/", OrderNovaPoshtaWaybillCreateAPIView.as_view(), name="order-waybill-create"),
    path("orders/<uuid:order_id>/waybill/update/", OrderNovaPoshtaWaybillUpdateAPIView.as_view(), name="order-waybill-update"),
    path("orders/<uuid:order_id>/waybill/delete/", OrderNovaPoshtaWaybillDeleteAPIView.as_view(), name="order-waybill-delete"),
    path("orders/<uuid:order_id>/waybill/sync/", OrderNovaPoshtaWaybillSyncAPIView.as_view(), name="order-waybill-sync"),
    path("orders/<uuid:order_id>/waybill/print/", OrderNovaPoshtaWaybillPrintAPIView.as_view(), name="order-waybill-print"),
    path("orders/<uuid:order_id>/payment/refresh/", BackofficeOrderPaymentRefreshAPIView.as_view(), name="order-payment-refresh"),
    path(
        "orders/<uuid:order_id>/payment/monobank/action/",
        BackofficeOrderPaymentMonobankActionAPIView.as_view(),
        name="order-payment-monobank-action",
    ),
    path("payments/monobank/settings/", BackofficeMonobankSettingsAPIView.as_view(), name="payments-monobank-settings"),
    path("payments/monobank/test-connection/", BackofficeMonobankConnectionTestAPIView.as_view(), name="payments-monobank-test"),
    path("payments/monobank/currency/", BackofficeMonobankCurrencyAPIView.as_view(), name="payments-monobank-currency"),
    path("payments/novapay/settings/", BackofficeNovaPaySettingsAPIView.as_view(), name="payments-novapay-settings"),
    path("payments/novapay/test-connection/", BackofficeNovaPayConnectionTestAPIView.as_view(), name="payments-novapay-test"),
    path("payments/liqpay/settings/", BackofficeLiqPaySettingsAPIView.as_view(), name="payments-liqpay-settings"),
    path("payments/liqpay/test-connection/", BackofficeLiqPayConnectionTestAPIView.as_view(), name="payments-liqpay-test"),
    path("rbac/meta/", BackofficeRbacMetaAPIView.as_view(), name="rbac-meta"),
    path("users/", BackofficeUserListCreateAPIView.as_view(), name="users-list-create"),
    path("users/<int:id>/", BackofficeUserRetrieveUpdateAPIView.as_view(), name="users-detail-update"),
    path("users/<int:user_id>/activate/", BackofficeUserActivateAPIView.as_view(), name="users-activate"),
    path("users/<int:user_id>/deactivate/", BackofficeUserDeactivateAPIView.as_view(), name="users-deactivate"),
    path("groups/", BackofficeGroupListCreateAPIView.as_view(), name="groups-list-create"),
    path("groups/<int:id>/", BackofficeGroupRetrieveUpdateAPIView.as_view(), name="groups-detail-update"),
    path("orders/", OrderOperationalListAPIView.as_view(), name="order-operational-list"),
    path("orders/<uuid:id>/", OrderOperationalDetailAPIView.as_view(), name="order-operational-detail"),
    path("orders/actions/confirm/", ConfirmOrderActionAPIView.as_view(), name="order-action-confirm"),
    path("orders/actions/awaiting-procurement/", MarkAwaitingProcurementActionAPIView.as_view(), name="order-action-awaiting-procurement"),
    path("orders/actions/reserve/", ReserveOrderItemsActionAPIView.as_view(), name="order-action-reserve"),
    path("orders/actions/ready-to-ship/", ReadyToShipOrderActionAPIView.as_view(), name="order-action-ready-to-ship"),
    path("orders/actions/cancel/", CancelOrderActionAPIView.as_view(), name="order-action-cancel"),
    path("orders/actions/delete/", DeleteOrderActionAPIView.as_view(), name="order-action-delete"),
    path("orders/actions/bulk-confirm/", BulkConfirmOrdersActionAPIView.as_view(), name="order-action-bulk-confirm"),
    path(
        "orders/actions/bulk-awaiting-procurement/",
        BulkAwaitingProcurementActionAPIView.as_view(),
        name="order-action-bulk-awaiting-procurement",
    ),
    path(
        "orders/actions/bulk-delete/",
        BulkDeleteOrdersActionAPIView.as_view(),
        name="order-action-bulk-delete",
    ),
    path("orders/supplier/gpl/all/", GplSupplierOrdersListAPIView.as_view(), name="order-gpl-list"),
    path(
        "orders/supplier/gpl/show/<int:supplier_order_id>/",
        GplSupplierOrderDetailAPIView.as_view(),
        name="order-gpl-detail",
    ),
    path("orders/supplier/gpl/payload/", GplOrderPayloadPreviewAPIView.as_view(), name="order-gpl-payload"),
    path("orders/supplier/gpl/store/", GplCreateOrderAPIView.as_view(), name="order-gpl-store"),
    path("orders/supplier/gpl/cancel/", GplCancelOrderAPIView.as_view(), name="order-gpl-cancel"),
    path(
        "orders/items/<uuid:item_id>/supplier-recommendation/",
        OrderItemSupplierRecommendationAPIView.as_view(),
        name="order-item-supplier-recommendation",
    ),
    path("orders/items/<uuid:item_id>/supplier-override/", OrderItemSupplierOverrideAPIView.as_view(), name="order-item-supplier-override"),
    path("procurement/suggestions/", ProcurementSuggestionsListAPIView.as_view(), name="procurement-suggestions-list"),
    path(
        "procurement/items/<uuid:item_id>/recommendation/",
        ProcurementItemRecommendationAPIView.as_view(),
        name="procurement-item-recommendation",
    ),
    path("actions/run-source/", RunImportSourceActionAPIView.as_view(), name="action-run-source"),
    path("actions/import-all/", ImportAllActionAPIView.as_view(), name="action-import-all"),
    path("actions/reprice-after-import/", RepriceAfterImportActionAPIView.as_view(), name="action-reprice-after-import"),
    path("actions/reindex-products/", ReindexProductsActionAPIView.as_view(), name="action-reindex-products"),
    path(
        "actions/bulk-move-products-category/",
        BulkMoveProductsCategoryActionAPIView.as_view(),
        name="action-bulk-move-products-category",
    ),
]
